-- 02_catalogo.sql - Pobla drenes_catastro y calidad_catastro (DREN-001.. / CAL-001..)
-- Los puntos unicos salen de la union de todas las tablas base (todos los anios).
\set ON_ERROR_STOP on

-- ============================================================
-- drenes_catastro
-- ============================================================
WITH un AS (
SELECT btrim(upper(coalesce(nullif(ubicacion,''),'(SIN NOMBRE)'))) || '|' || coalesce(cooreste::text,'') || '|' || coalesce(coornorte::text,'') AS clv, geom, cooreste, coornorte, zona, cota, departamento, provincia, distrito, ubicacion, descripcion, aaa, ala, uh, fechamonitoreo::date AS fechamonitoreo, fechamonitoreo::date + horamonitoreo::time AS horamonitoreo, orden, ce, ph, std, t, turbidez, nitratos, nitritos, cromohexavalente, cobre, manganeso, sulfatos, hierro, zinc, cloruros, coliformestotales, coliformestermotolerantes, escherichiacoli, "dureza" AS "durezatotal", NULL::double precision AS "calcio", NULL::double precision AS "cloruro", NULL::double precision AS "potasio", NULL::double precision AS "sodio", NULL::double precision AS "amonio", NULL::double precision AS "magnesio", "observacion" AS "observaciones", CASE extract(MONTH FROM fechamonitoreo::date)::int WHEN 1 THEN 'ENERO' WHEN 2 THEN 'FEBRERO' WHEN 3 THEN 'MARZO' WHEN 4 THEN 'ABRIL' WHEN 5 THEN 'MAYO' WHEN 6 THEN 'JUNIO' WHEN 7 THEN 'JULIO' WHEN 8 THEN 'AGOSTO' WHEN 9 THEN 'SETIEMBRE' WHEN 10 THEN 'OCTUBRE' WHEN 11 THEN 'NOVIEMBRE' WHEN 12 THEN 'DICIEMBRE' END || ' ' || extract(YEAR FROM fechamonitoreo::date)::int AS campana, 'drene' AS tipo
FROM calidadaguadrenada2022.monitoreodrenajeabril WHERE (fechamonitoreo IS NOT NULL OR cooreste IS NOT NULL OR coornorte IS NOT NULL OR ce IS NOT NULL OR ph IS NOT NULL OR turbidez IS NOT NULL)
UNION ALL
SELECT btrim(upper(coalesce(nullif(ubicacion,''),'(SIN NOMBRE)'))) || '|' || coalesce(cooreste::text,'') || '|' || coalesce(coornorte::text,'') AS clv, geom, cooreste, coornorte, zona, cota, departamento, provincia, distrito, ubicacion, descripcion, aaa, ala, uh, fechamonitoreo::date AS fechamonitoreo, fechamonitoreo::date + horamonitoreo::time AS horamonitoreo, orden, ce, ph, std, t, turbidez, nitratos, nitritos, cromohexavalente, cobre, manganeso, sulfatos, hierro, zinc, cloruros, coliformestotales, coliformestermotolerantes, escherichiacoli, "dureza" AS "durezatotal", NULL::double precision AS "calcio", NULL::double precision AS "cloruro", NULL::double precision AS "potasio", NULL::double precision AS "sodio", NULL::double precision AS "amonio", NULL::double precision AS "magnesio", "observacion" AS "observaciones", CASE extract(MONTH FROM fechamonitoreo::date)::int WHEN 1 THEN 'ENERO' WHEN 2 THEN 'FEBRERO' WHEN 3 THEN 'MARZO' WHEN 4 THEN 'ABRIL' WHEN 5 THEN 'MAYO' WHEN 6 THEN 'JUNIO' WHEN 7 THEN 'JULIO' WHEN 8 THEN 'AGOSTO' WHEN 9 THEN 'SETIEMBRE' WHEN 10 THEN 'OCTUBRE' WHEN 11 THEN 'NOVIEMBRE' WHEN 12 THEN 'DICIEMBRE' END || ' ' || extract(YEAR FROM fechamonitoreo::date)::int AS campana, 'drene' AS tipo
FROM calidadaguadrenada2022.monitoreodrenajeagosto WHERE (fechamonitoreo IS NOT NULL OR cooreste IS NOT NULL OR coornorte IS NOT NULL OR ce IS NOT NULL OR ph IS NOT NULL OR turbidez IS NOT NULL)
UNION ALL
SELECT btrim(upper(coalesce(nullif(ubicacion,''),'(SIN NOMBRE)'))) || '|' || coalesce(cooreste::text,'') || '|' || coalesce(coornorte::text,'') AS clv, geom, cooreste, coornorte, zona, cota, departamento, provincia, distrito, ubicacion, descripcion, aaa, ala, uh, fechamonitoreo::date AS fechamonitoreo, fechamonitoreo::date + horamonitoreo::time AS horamonitoreo, orden, ce, ph, std, t, turbidez, nitratos, nitritos, cromohexavalente, cobre, manganeso, sulfatos, hierro, zinc, cloruros, coliformestotales, coliformestermotolerantes, escherichiacoli, "dureza" AS "durezatotal", NULL::double precision AS "calcio", NULL::double precision AS "cloruro", NULL::double precision AS "potasio", NULL::double precision AS "sodio", NULL::double precision AS "amonio", NULL::double precision AS "magnesio", "observacion" AS "observaciones", CASE extract(MONTH FROM fechamonitoreo::date)::int WHEN 1 THEN 'ENERO' WHEN 2 THEN 'FEBRERO' WHEN 3 THEN 'MARZO' WHEN 4 THEN 'ABRIL' WHEN 5 THEN 'MAYO' WHEN 6 THEN 'JUNIO' WHEN 7 THEN 'JULIO' WHEN 8 THEN 'AGOSTO' WHEN 9 THEN 'SETIEMBRE' WHEN 10 THEN 'OCTUBRE' WHEN 11 THEN 'NOVIEMBRE' WHEN 12 THEN 'DICIEMBRE' END || ' ' || extract(YEAR FROM fechamonitoreo::date)::int AS campana, 'drene' AS tipo
FROM calidadaguadrenada2022.monitoreodrenajediciembre WHERE (fechamonitoreo IS NOT NULL OR cooreste IS NOT NULL OR coornorte IS NOT NULL OR ce IS NOT NULL OR ph IS NOT NULL OR turbidez IS NOT NULL)
UNION ALL
SELECT btrim(upper(coalesce(nullif(ubicacion,''),'(SIN NOMBRE)'))) || '|' || coalesce(cooreste::text,'') || '|' || coalesce(coornorte::text,'') AS clv, geom, cooreste, coornorte, zona, cota, departamento, provincia, distrito, ubicacion, descripcion, aaa, ala, uh, fechamonitoreo::date AS fechamonitoreo, fechamonitoreo::date + horamonitoreo::time AS horamonitoreo, orden, ce, ph, std, t, turbidez, nitratos, nitritos, cromohexavalente, cobre, manganeso, sulfatos, hierro, zinc, cloruros, coliformestotales, coliformestermotolerantes, escherichiacoli, "dureza" AS "durezatotal", NULL::double precision AS "calcio", NULL::double precision AS "cloruro", NULL::double precision AS "potasio", NULL::double precision AS "sodio", NULL::double precision AS "amonio", NULL::double precision AS "magnesio", "observacion" AS "observaciones", CASE extract(MONTH FROM fechamonitoreo::date)::int WHEN 1 THEN 'ENERO' WHEN 2 THEN 'FEBRERO' WHEN 3 THEN 'MARZO' WHEN 4 THEN 'ABRIL' WHEN 5 THEN 'MAYO' WHEN 6 THEN 'JUNIO' WHEN 7 THEN 'JULIO' WHEN 8 THEN 'AGOSTO' WHEN 9 THEN 'SETIEMBRE' WHEN 10 THEN 'OCTUBRE' WHEN 11 THEN 'NOVIEMBRE' WHEN 12 THEN 'DICIEMBRE' END || ' ' || extract(YEAR FROM fechamonitoreo::date)::int AS campana, 'drene' AS tipo
FROM calidadaguadrenada2022.monitoreodrenajejulio WHERE (fechamonitoreo IS NOT NULL OR cooreste IS NOT NULL OR coornorte IS NOT NULL OR ce IS NOT NULL OR ph IS NOT NULL OR turbidez IS NOT NULL)
UNION ALL
SELECT btrim(upper(coalesce(nullif(ubicacion,''),'(SIN NOMBRE)'))) || '|' || coalesce(cooreste::text,'') || '|' || coalesce(coornorte::text,'') AS clv, geom, cooreste, coornorte, zona, cota, departamento, provincia, distrito, ubicacion, descripcion, aaa, ala, uh, fechamonitoreo::date AS fechamonitoreo, fechamonitoreo::date + horamonitoreo::time AS horamonitoreo, orden, ce, ph, std, t, turbidez, nitratos, nitritos, cromohexavalente, cobre, manganeso, sulfatos, hierro, zinc, cloruros, coliformestotales, coliformestermotolerantes, escherichiacoli, "dureza" AS "durezatotal", NULL::double precision AS "calcio", NULL::double precision AS "cloruro", NULL::double precision AS "potasio", NULL::double precision AS "sodio", NULL::double precision AS "amonio", NULL::double precision AS "magnesio", "observacion" AS "observaciones", CASE extract(MONTH FROM fechamonitoreo::date)::int WHEN 1 THEN 'ENERO' WHEN 2 THEN 'FEBRERO' WHEN 3 THEN 'MARZO' WHEN 4 THEN 'ABRIL' WHEN 5 THEN 'MAYO' WHEN 6 THEN 'JUNIO' WHEN 7 THEN 'JULIO' WHEN 8 THEN 'AGOSTO' WHEN 9 THEN 'SETIEMBRE' WHEN 10 THEN 'OCTUBRE' WHEN 11 THEN 'NOVIEMBRE' WHEN 12 THEN 'DICIEMBRE' END || ' ' || extract(YEAR FROM fechamonitoreo::date)::int AS campana, 'drene' AS tipo
FROM calidadaguadrenada2022.monitoreodrenajejunio WHERE (fechamonitoreo IS NOT NULL OR cooreste IS NOT NULL OR coornorte IS NOT NULL OR ce IS NOT NULL OR ph IS NOT NULL OR turbidez IS NOT NULL)
UNION ALL
SELECT btrim(upper(coalesce(nullif(ubicacion,''),'(SIN NOMBRE)'))) || '|' || coalesce(cooreste::text,'') || '|' || coalesce(coornorte::text,'') AS clv, geom, cooreste, coornorte, zona, cota, departamento, provincia, distrito, ubicacion, descripcion, aaa, ala, uh, fechamonitoreo::date AS fechamonitoreo, fechamonitoreo::date + horamonitoreo::time AS horamonitoreo, orden, ce, ph, std, t, turbidez, nitratos, nitritos, cromohexavalente, cobre, manganeso, sulfatos, hierro, zinc, cloruros, coliformestotales, coliformestermotolerantes, escherichiacoli, "dureza" AS "durezatotal", NULL::double precision AS "calcio", NULL::double precision AS "cloruro", NULL::double precision AS "potasio", NULL::double precision AS "sodio", NULL::double precision AS "amonio", NULL::double precision AS "magnesio", "observacion" AS "observaciones", CASE extract(MONTH FROM fechamonitoreo::date)::int WHEN 1 THEN 'ENERO' WHEN 2 THEN 'FEBRERO' WHEN 3 THEN 'MARZO' WHEN 4 THEN 'ABRIL' WHEN 5 THEN 'MAYO' WHEN 6 THEN 'JUNIO' WHEN 7 THEN 'JULIO' WHEN 8 THEN 'AGOSTO' WHEN 9 THEN 'SETIEMBRE' WHEN 10 THEN 'OCTUBRE' WHEN 11 THEN 'NOVIEMBRE' WHEN 12 THEN 'DICIEMBRE' END || ' ' || extract(YEAR FROM fechamonitoreo::date)::int AS campana, 'drene' AS tipo
FROM calidadaguadrenada2022.monitoreodrenajemarzo WHERE (fechamonitoreo IS NOT NULL OR cooreste IS NOT NULL OR coornorte IS NOT NULL OR ce IS NOT NULL OR ph IS NOT NULL OR turbidez IS NOT NULL)
UNION ALL
SELECT btrim(upper(coalesce(nullif(ubicacion,''),'(SIN NOMBRE)'))) || '|' || coalesce(cooreste::text,'') || '|' || coalesce(coornorte::text,'') AS clv, geom, cooreste, coornorte, zona, cota, departamento, provincia, distrito, ubicacion, descripcion, aaa, ala, uh, fechamonitoreo::date AS fechamonitoreo, fechamonitoreo::date + horamonitoreo::time AS horamonitoreo, orden, ce, ph, std, t, turbidez, nitratos, nitritos, cromohexavalente, cobre, manganeso, sulfatos, hierro, zinc, cloruros, coliformestotales, coliformestermotolerantes, escherichiacoli, "dureza" AS "durezatotal", NULL::double precision AS "calcio", NULL::double precision AS "cloruro", NULL::double precision AS "potasio", NULL::double precision AS "sodio", NULL::double precision AS "amonio", NULL::double precision AS "magnesio", "observacion" AS "observaciones", CASE extract(MONTH FROM fechamonitoreo::date)::int WHEN 1 THEN 'ENERO' WHEN 2 THEN 'FEBRERO' WHEN 3 THEN 'MARZO' WHEN 4 THEN 'ABRIL' WHEN 5 THEN 'MAYO' WHEN 6 THEN 'JUNIO' WHEN 7 THEN 'JULIO' WHEN 8 THEN 'AGOSTO' WHEN 9 THEN 'SETIEMBRE' WHEN 10 THEN 'OCTUBRE' WHEN 11 THEN 'NOVIEMBRE' WHEN 12 THEN 'DICIEMBRE' END || ' ' || extract(YEAR FROM fechamonitoreo::date)::int AS campana, 'drene' AS tipo
FROM calidadaguadrenada2022.monitoreodrenajenoviembre WHERE (fechamonitoreo IS NOT NULL OR cooreste IS NOT NULL OR coornorte IS NOT NULL OR ce IS NOT NULL OR ph IS NOT NULL OR turbidez IS NOT NULL)
UNION ALL
SELECT btrim(upper(coalesce(nullif(ubicacion,''),'(SIN NOMBRE)'))) || '|' || coalesce(cooreste::text,'') || '|' || coalesce(coornorte::text,'') AS clv, geom, cooreste, coornorte, zona, cota, departamento, provincia, distrito, ubicacion, descripcion, aaa, ala, uh, fechamonitoreo::date AS fechamonitoreo, fechamonitoreo::date + horamonitoreo::time AS horamonitoreo, orden, ce, ph, std, t, turbidez, nitratos, nitritos, cromohexavalente, cobre, manganeso, sulfatos, hierro, zinc, cloruros, coliformestotales, coliformestermotolerantes, escherichiacoli, "dureza" AS "durezatotal", NULL::double precision AS "calcio", NULL::double precision AS "cloruro", NULL::double precision AS "potasio", NULL::double precision AS "sodio", NULL::double precision AS "amonio", NULL::double precision AS "magnesio", "observacion" AS "observaciones", CASE extract(MONTH FROM fechamonitoreo::date)::int WHEN 1 THEN 'ENERO' WHEN 2 THEN 'FEBRERO' WHEN 3 THEN 'MARZO' WHEN 4 THEN 'ABRIL' WHEN 5 THEN 'MAYO' WHEN 6 THEN 'JUNIO' WHEN 7 THEN 'JULIO' WHEN 8 THEN 'AGOSTO' WHEN 9 THEN 'SETIEMBRE' WHEN 10 THEN 'OCTUBRE' WHEN 11 THEN 'NOVIEMBRE' WHEN 12 THEN 'DICIEMBRE' END || ' ' || extract(YEAR FROM fechamonitoreo::date)::int AS campana, 'drene' AS tipo
FROM calidadaguadrenada2022.monitoreodrenajeoctubre WHERE (fechamonitoreo IS NOT NULL OR cooreste IS NOT NULL OR coornorte IS NOT NULL OR ce IS NOT NULL OR ph IS NOT NULL OR turbidez IS NOT NULL)
UNION ALL
SELECT btrim(upper(coalesce(nullif(ubicacion,''),'(SIN NOMBRE)'))) || '|' || coalesce(cooreste::text,'') || '|' || coalesce(coornorte::text,'') AS clv, geom, cooreste, coornorte, zona, cota, departamento, provincia, distrito, ubicacion, descripcion, aaa, ala, uh, fechamonitoreo::date AS fechamonitoreo, fechamonitoreo::date + horamonitoreo::time AS horamonitoreo, orden, ce, ph, std, t, turbidez, nitratos, nitritos, cromohexavalente, cobre, manganeso, sulfatos, hierro, zinc, cloruros, coliformestotales, coliformestermotolerantes, escherichiacoli, "dureza" AS "durezatotal", NULL::double precision AS "calcio", NULL::double precision AS "cloruro", NULL::double precision AS "potasio", NULL::double precision AS "sodio", NULL::double precision AS "amonio", NULL::double precision AS "magnesio", "observacion" AS "observaciones", CASE extract(MONTH FROM fechamonitoreo::date)::int WHEN 1 THEN 'ENERO' WHEN 2 THEN 'FEBRERO' WHEN 3 THEN 'MARZO' WHEN 4 THEN 'ABRIL' WHEN 5 THEN 'MAYO' WHEN 6 THEN 'JUNIO' WHEN 7 THEN 'JULIO' WHEN 8 THEN 'AGOSTO' WHEN 9 THEN 'SETIEMBRE' WHEN 10 THEN 'OCTUBRE' WHEN 11 THEN 'NOVIEMBRE' WHEN 12 THEN 'DICIEMBRE' END || ' ' || extract(YEAR FROM fechamonitoreo::date)::int AS campana, 'drene' AS tipo
FROM calidadaguadrenada2022.monitoreodrenajesetiembre WHERE (fechamonitoreo IS NOT NULL OR cooreste IS NOT NULL OR coornorte IS NOT NULL OR ce IS NOT NULL OR ph IS NOT NULL OR turbidez IS NOT NULL)
UNION ALL
SELECT btrim(upper(coalesce(nullif(ubicacion,''),'(SIN NOMBRE)'))) || '|' || coalesce(cooreste::text,'') || '|' || coalesce(coornorte::text,'') AS clv, geom, cooreste, coornorte, zona, cota, departamento, provincia, distrito, ubicacion, descripcion, aaa, ala, uh, fechamonitoreo::date AS fechamonitoreo, fechamonitoreo::date + horamonitoreo::time AS horamonitoreo, orden, ce, ph, std, t, turbidez, nitratos, nitritos, cromohexavalente, cobre, manganeso, sulfatos, hierro, zinc, cloruros, coliformestotales, coliformestermotolerantes, escherichiacoli, "dureza" AS "durezatotal", NULL::double precision AS "calcio", NULL::double precision AS "cloruro", NULL::double precision AS "potasio", NULL::double precision AS "sodio", NULL::double precision AS "amonio", NULL::double precision AS "magnesio", "observacion" AS "observaciones", CASE extract(MONTH FROM fechamonitoreo::date)::int WHEN 1 THEN 'ENERO' WHEN 2 THEN 'FEBRERO' WHEN 3 THEN 'MARZO' WHEN 4 THEN 'ABRIL' WHEN 5 THEN 'MAYO' WHEN 6 THEN 'JUNIO' WHEN 7 THEN 'JULIO' WHEN 8 THEN 'AGOSTO' WHEN 9 THEN 'SETIEMBRE' WHEN 10 THEN 'OCTUBRE' WHEN 11 THEN 'NOVIEMBRE' WHEN 12 THEN 'DICIEMBRE' END || ' ' || extract(YEAR FROM fechamonitoreo::date)::int AS campana, 'drene' AS tipo
FROM calidadaguadrenada2023.monitoreodrenajeabril WHERE (fechamonitoreo IS NOT NULL OR cooreste IS NOT NULL OR coornorte IS NOT NULL OR ce IS NOT NULL OR ph IS NOT NULL OR turbidez IS NOT NULL)
UNION ALL
SELECT btrim(upper(coalesce(nullif(ubicacion,''),'(SIN NOMBRE)'))) || '|' || coalesce(cooreste::text,'') || '|' || coalesce(coornorte::text,'') AS clv, geom, cooreste, coornorte, zona, cota, departamento, provincia, distrito, ubicacion, descripcion, aaa, ala, uh, fechamonitoreo::date AS fechamonitoreo, fechamonitoreo::date + horamonitoreo::time AS horamonitoreo, orden, ce, ph, std, t, turbidez, nitratos, nitritos, cromohexavalente, cobre, manganeso, sulfatos, hierro, zinc, cloruros, coliformestotales, coliformestermotolerantes, escherichiacoli, "dureza" AS "durezatotal", NULL::double precision AS "calcio", NULL::double precision AS "cloruro", NULL::double precision AS "potasio", NULL::double precision AS "sodio", NULL::double precision AS "amonio", NULL::double precision AS "magnesio", "observacion" AS "observaciones", CASE extract(MONTH FROM fechamonitoreo::date)::int WHEN 1 THEN 'ENERO' WHEN 2 THEN 'FEBRERO' WHEN 3 THEN 'MARZO' WHEN 4 THEN 'ABRIL' WHEN 5 THEN 'MAYO' WHEN 6 THEN 'JUNIO' WHEN 7 THEN 'JULIO' WHEN 8 THEN 'AGOSTO' WHEN 9 THEN 'SETIEMBRE' WHEN 10 THEN 'OCTUBRE' WHEN 11 THEN 'NOVIEMBRE' WHEN 12 THEN 'DICIEMBRE' END || ' ' || extract(YEAR FROM fechamonitoreo::date)::int AS campana, 'drene' AS tipo
FROM calidadaguadrenada2023.monitoreodrenajejulio WHERE (fechamonitoreo IS NOT NULL OR cooreste IS NOT NULL OR coornorte IS NOT NULL OR ce IS NOT NULL OR ph IS NOT NULL OR turbidez IS NOT NULL)
UNION ALL
SELECT btrim(upper(coalesce(nullif(ubicacion,''),'(SIN NOMBRE)'))) || '|' || coalesce(cooreste::text,'') || '|' || coalesce(coornorte::text,'') AS clv, geom, cooreste, coornorte, zona, cota, departamento, provincia, distrito, ubicacion, descripcion, aaa, ala, uh, fechamonitoreo::date AS fechamonitoreo, fechamonitoreo::date + horamonitoreo::time AS horamonitoreo, orden, ce, ph, std, t, turbidez, nitratos, nitritos, cromohexavalente, cobre, manganeso, sulfatos, hierro, zinc, cloruros, coliformestotales, coliformestermotolerantes, escherichiacoli, "dureza" AS "durezatotal", NULL::double precision AS "calcio", NULL::double precision AS "cloruro", NULL::double precision AS "potasio", NULL::double precision AS "sodio", NULL::double precision AS "amonio", NULL::double precision AS "magnesio", "observacion" AS "observaciones", CASE extract(MONTH FROM fechamonitoreo::date)::int WHEN 1 THEN 'ENERO' WHEN 2 THEN 'FEBRERO' WHEN 3 THEN 'MARZO' WHEN 4 THEN 'ABRIL' WHEN 5 THEN 'MAYO' WHEN 6 THEN 'JUNIO' WHEN 7 THEN 'JULIO' WHEN 8 THEN 'AGOSTO' WHEN 9 THEN 'SETIEMBRE' WHEN 10 THEN 'OCTUBRE' WHEN 11 THEN 'NOVIEMBRE' WHEN 12 THEN 'DICIEMBRE' END || ' ' || extract(YEAR FROM fechamonitoreo::date)::int AS campana, 'drene' AS tipo
FROM calidadaguadrenada2023.monitoreodrenajejunio WHERE (fechamonitoreo IS NOT NULL OR cooreste IS NOT NULL OR coornorte IS NOT NULL OR ce IS NOT NULL OR ph IS NOT NULL OR turbidez IS NOT NULL)
UNION ALL
SELECT btrim(upper(coalesce(nullif(ubicacion,''),'(SIN NOMBRE)'))) || '|' || coalesce(cooreste::text,'') || '|' || coalesce(coornorte::text,'') AS clv, geom, cooreste, coornorte, zona, cota, departamento, provincia, distrito, ubicacion, descripcion, aaa, ala, uh, fechamonitoreo::date AS fechamonitoreo, fechamonitoreo::date + horamonitoreo::time AS horamonitoreo, orden, ce, ph, std, t, turbidez, nitratos, nitritos, cromohexavalente, cobre, manganeso, sulfatos, hierro, zinc, cloruros, coliformestotales, coliformestermotolerantes, escherichiacoli, "dureza" AS "durezatotal", NULL::double precision AS "calcio", NULL::double precision AS "cloruro", NULL::double precision AS "potasio", NULL::double precision AS "sodio", NULL::double precision AS "amonio", NULL::double precision AS "magnesio", "observacion" AS "observaciones", CASE extract(MONTH FROM fechamonitoreo::date)::int WHEN 1 THEN 'ENERO' WHEN 2 THEN 'FEBRERO' WHEN 3 THEN 'MARZO' WHEN 4 THEN 'ABRIL' WHEN 5 THEN 'MAYO' WHEN 6 THEN 'JUNIO' WHEN 7 THEN 'JULIO' WHEN 8 THEN 'AGOSTO' WHEN 9 THEN 'SETIEMBRE' WHEN 10 THEN 'OCTUBRE' WHEN 11 THEN 'NOVIEMBRE' WHEN 12 THEN 'DICIEMBRE' END || ' ' || extract(YEAR FROM fechamonitoreo::date)::int AS campana, 'drene' AS tipo
FROM calidadaguadrenada2023.monitoreodrenajesetiembre WHERE (fechamonitoreo IS NOT NULL OR cooreste IS NOT NULL OR coornorte IS NOT NULL OR ce IS NOT NULL OR ph IS NOT NULL OR turbidez IS NOT NULL)
UNION ALL
SELECT btrim(upper(coalesce(nullif(ubicacion,''),'(SIN NOMBRE)'))) || '|' || coalesce(cooreste::text,'') || '|' || coalesce(coornorte::text,'') AS clv, geom, cooreste, coornorte, zona, cota, departamento, provincia, distrito, ubicacion, descripcion, aaa, ala, uh, fechamonitoreo::date AS fechamonitoreo, fechamonitoreo::date + horamonitoreo::time AS horamonitoreo, orden, ce, ph, std, t, turbidez, nitratos, nitritos, cromohexavalente, cobre, manganeso, sulfatos, hierro, zinc, cloruros, coliformestotales, coliformestermotolerantes, escherichiacoli, "durezatotal", "calcio", "cloruro", "potasio", "sodio", "amonio", "magnesio", "observacion" AS "observaciones", CASE extract(MONTH FROM fechamonitoreo::date)::int WHEN 1 THEN 'ENERO' WHEN 2 THEN 'FEBRERO' WHEN 3 THEN 'MARZO' WHEN 4 THEN 'ABRIL' WHEN 5 THEN 'MAYO' WHEN 6 THEN 'JUNIO' WHEN 7 THEN 'JULIO' WHEN 8 THEN 'AGOSTO' WHEN 9 THEN 'SETIEMBRE' WHEN 10 THEN 'OCTUBRE' WHEN 11 THEN 'NOVIEMBRE' WHEN 12 THEN 'DICIEMBRE' END || ' ' || extract(YEAR FROM fechamonitoreo::date)::int AS campana, 'drene' AS tipo
FROM calidadaguadrenada2024.monitoreodrenajeabril WHERE (fechamonitoreo IS NOT NULL OR cooreste IS NOT NULL OR coornorte IS NOT NULL OR ce IS NOT NULL OR ph IS NOT NULL OR turbidez IS NOT NULL)
UNION ALL
SELECT btrim(upper(coalesce(nullif(ubicacion,''),'(SIN NOMBRE)'))) || '|' || coalesce(cooreste::text,'') || '|' || coalesce(coornorte::text,'') AS clv, geom, cooreste, coornorte, zona, cota, departamento, provincia, distrito, ubicacion, descripcion, aaa, ala, uh, fechamonitoreo::date AS fechamonitoreo, fechamonitoreo::date + horamonitoreo::time AS horamonitoreo, orden, ce, ph, std, t, turbidez, nitratos, nitritos, cromohexavalente, cobre, manganeso, sulfatos, hierro, zinc, cloruros, coliformestotales, coliformestermotolerantes, escherichiacoli, "durezatotal", "calcio", "cloruro", "potasio", "sodio", "amonio", "magnesio", "observacion" AS "observaciones", CASE extract(MONTH FROM fechamonitoreo::date)::int WHEN 1 THEN 'ENERO' WHEN 2 THEN 'FEBRERO' WHEN 3 THEN 'MARZO' WHEN 4 THEN 'ABRIL' WHEN 5 THEN 'MAYO' WHEN 6 THEN 'JUNIO' WHEN 7 THEN 'JULIO' WHEN 8 THEN 'AGOSTO' WHEN 9 THEN 'SETIEMBRE' WHEN 10 THEN 'OCTUBRE' WHEN 11 THEN 'NOVIEMBRE' WHEN 12 THEN 'DICIEMBRE' END || ' ' || extract(YEAR FROM fechamonitoreo::date)::int AS campana, 'drene' AS tipo
FROM calidadaguadrenada2024.monitoreodrenajenoviembre WHERE (fechamonitoreo IS NOT NULL OR cooreste IS NOT NULL OR coornorte IS NOT NULL OR ce IS NOT NULL OR ph IS NOT NULL OR turbidez IS NOT NULL)
UNION ALL
SELECT btrim(upper(coalesce(nullif(ubicacion,''),'(SIN NOMBRE)'))) || '|' || coalesce(cooreste::text,'') || '|' || coalesce(coornorte::text,'') AS clv, geom, cooreste, coornorte, zona, cota, departamento, provincia, distrito, ubicacion, descripcion, aaa, ala, uh, fechamonitoreo::date AS fechamonitoreo, fechamonitoreo::date + horamonitoreo::time AS horamonitoreo, orden, ce, ph, std, t, turbidez, nitratos, nitritos, cromohexavalente, cobre, manganeso, sulfatos, hierro, zinc, cloruros, coliformestotales, coliformestermotolerantes, escherichiacoli, "durezatotal", "calcio", "cloruro", "potasio", "sodio", "amonio", "magnesio", "observaciones", CASE extract(MONTH FROM fechamonitoreo::date)::int WHEN 1 THEN 'ENERO' WHEN 2 THEN 'FEBRERO' WHEN 3 THEN 'MARZO' WHEN 4 THEN 'ABRIL' WHEN 5 THEN 'MAYO' WHEN 6 THEN 'JUNIO' WHEN 7 THEN 'JULIO' WHEN 8 THEN 'AGOSTO' WHEN 9 THEN 'SETIEMBRE' WHEN 10 THEN 'OCTUBRE' WHEN 11 THEN 'NOVIEMBRE' WHEN 12 THEN 'DICIEMBRE' END || ' ' || extract(YEAR FROM fechamonitoreo::date)::int AS campana, 'drene' AS tipo
FROM calidadaguadrenada2025.monitoreodrenajefebrero WHERE (fechamonitoreo IS NOT NULL OR cooreste IS NOT NULL OR coornorte IS NOT NULL OR ce IS NOT NULL OR ph IS NOT NULL OR turbidez IS NOT NULL)
UNION ALL
SELECT btrim(upper(coalesce(nullif(ubicacion,''),'(SIN NOMBRE)'))) || '|' || coalesce(cooreste::text,'') || '|' || coalesce(coornorte::text,'') AS clv, geom, cooreste, coornorte, zona, cota, departamento, provincia, distrito, ubicacion, descripcion, aaa, ala, uh, fechamonitoreo::date AS fechamonitoreo, fechamonitoreo::date + horamonitoreo::time AS horamonitoreo, orden, ce, ph, std, t, turbidez, nitratos, nitritos, cromohexavalente, cobre, manganeso, sulfatos, hierro, zinc, cloruros, coliformestotales, coliformestermotolerantes, escherichiacoli, "durezatotal", "calcio", "cloruro", "potasio", "sodio", "amonio", "magnesio", "observaciones", CASE extract(MONTH FROM fechamonitoreo::date)::int WHEN 1 THEN 'ENERO' WHEN 2 THEN 'FEBRERO' WHEN 3 THEN 'MARZO' WHEN 4 THEN 'ABRIL' WHEN 5 THEN 'MAYO' WHEN 6 THEN 'JUNIO' WHEN 7 THEN 'JULIO' WHEN 8 THEN 'AGOSTO' WHEN 9 THEN 'SETIEMBRE' WHEN 10 THEN 'OCTUBRE' WHEN 11 THEN 'NOVIEMBRE' WHEN 12 THEN 'DICIEMBRE' END || ' ' || extract(YEAR FROM fechamonitoreo::date)::int AS campana, 'drene' AS tipo
FROM calidadaguadrenada2025.monitoreodrenajejulio WHERE (fechamonitoreo IS NOT NULL OR cooreste IS NOT NULL OR coornorte IS NOT NULL OR ce IS NOT NULL OR ph IS NOT NULL OR turbidez IS NOT NULL)
UNION ALL
SELECT btrim(upper(coalesce(nullif(ubicacion,''),'(SIN NOMBRE)'))) || '|' || coalesce(cooreste::text,'') || '|' || coalesce(coornorte::text,'') AS clv, geom, cooreste, coornorte, zona, cota, departamento, provincia, distrito, ubicacion, descripcion, aaa, ala, uh, fechamonitoreo::date AS fechamonitoreo, fechamonitoreo::date + horamonitoreo::time AS horamonitoreo, orden, ce, ph, std, t, turbidez, nitratos, nitritos, cromohexavalente, cobre, manganeso, sulfatos, hierro, zinc, cloruros, coliformestotales, coliformestermotolerantes, escherichiacoli, "durezatotal", "calcio", "cloruro", "potasio", "sodio", "amonio", "magnesio", "observaciones", CASE extract(MONTH FROM fechamonitoreo::date)::int WHEN 1 THEN 'ENERO' WHEN 2 THEN 'FEBRERO' WHEN 3 THEN 'MARZO' WHEN 4 THEN 'ABRIL' WHEN 5 THEN 'MAYO' WHEN 6 THEN 'JUNIO' WHEN 7 THEN 'JULIO' WHEN 8 THEN 'AGOSTO' WHEN 9 THEN 'SETIEMBRE' WHEN 10 THEN 'OCTUBRE' WHEN 11 THEN 'NOVIEMBRE' WHEN 12 THEN 'DICIEMBRE' END || ' ' || extract(YEAR FROM fechamonitoreo::date)::int AS campana, 'drene' AS tipo
FROM calidadaguadrenada2025.monitoreodrenajeoctubre WHERE (fechamonitoreo IS NOT NULL OR cooreste IS NOT NULL OR coornorte IS NOT NULL OR ce IS NOT NULL OR ph IS NOT NULL OR turbidez IS NOT NULL)
UNION ALL
SELECT btrim(upper(coalesce(nullif(ubicacion,''),'(SIN NOMBRE)'))) || '|' || coalesce(cooreste::text,'') || '|' || coalesce(coornorte::text,'') AS clv, geom, cooreste, coornorte, zona, cota, departamento, provincia, distrito, ubicacion, descripcion, aaa, ala, uh, fechamonitoreo::date AS fechamonitoreo, fechamonitoreo::date + horamonitoreo::time AS horamonitoreo, orden, ce, ph, std, t, turbidez, nitratos, nitritos, cromohexavalente, cobre, manganeso, sulfatos, hierro, zinc, cloruros, coliformestotales, coliformestermotolerantes, escherichiacoli, "durezatotal", "calcio", "cloruro", "potasio", "sodio", "amonio", "magnesio", "observaciones", CASE extract(MONTH FROM fechamonitoreo::date)::int WHEN 1 THEN 'ENERO' WHEN 2 THEN 'FEBRERO' WHEN 3 THEN 'MARZO' WHEN 4 THEN 'ABRIL' WHEN 5 THEN 'MAYO' WHEN 6 THEN 'JUNIO' WHEN 7 THEN 'JULIO' WHEN 8 THEN 'AGOSTO' WHEN 9 THEN 'SETIEMBRE' WHEN 10 THEN 'OCTUBRE' WHEN 11 THEN 'NOVIEMBRE' WHEN 12 THEN 'DICIEMBRE' END || ' ' || extract(YEAR FROM fechamonitoreo::date)::int AS campana, 'drene' AS tipo
FROM calidadaguadrenada2026.monitoreodrenajemarzo WHERE (fechamonitoreo IS NOT NULL OR cooreste IS NOT NULL OR coornorte IS NOT NULL OR ce IS NOT NULL OR ph IS NOT NULL OR turbidez IS NOT NULL)
),
dedup AS (
    SELECT DISTINCT ON (clv) *
    FROM un
    WHERE clv IS NOT NULL
    ORDER BY clv,
        (cooreste IS NOT NULL) DESC,
        (fechamonitoreo IS NOT NULL) DESC,
        fechamonitoreo
),
ordered AS (
    SELECT *, row_number() OVER (ORDER BY clv) AS rn FROM dedup
)
INSERT INTO hidrologia.drenes_catastro
    (id_dren, geom, cooreste, coornorte, zona, cota, departamento, provincia, distrito,
     ubicacion, descripcion, aaa, ala, uh, fechainventario, observaciones)
SELECT 'DREN-' || lpad(rn::text, 3, '0'),
       geom, cooreste, coornorte, zona, cota, departamento, provincia, distrito,
       ubicacion, descripcion, aaa, ala, uh, fechamonitoreo, observaciones
FROM ordered;

-- ============================================================
-- calidad_catastro
-- ============================================================
WITH un AS (
SELECT btrim(upper(coalesce(nullif(ubicacion,''),'(SIN NOMBRE)'))) || '|' || coalesce(cooreste::text,'') || '|' || coalesce(coornorte::text,'') AS clv, geom, cooreste, coornorte, zona, cota, departamento, provincia, distrito, ubicacion, descripcion, aaa, ala, uh, fechamonitoreo::date AS fechamonitoreo, fechamonitoreo::date + horamonitoreo::time AS horamonitoreo, orden, ce, ph, std, t, turbidez, nitratos, nitritos, cromohexavalente, cobre, manganeso, sulfatos, hierro, zinc, cloruros, coliformestotales, coliformestermotolerantes, escherichiacoli, "durezatotal", NULL::double precision AS "calcio", NULL::double precision AS "cloruro", NULL::double precision AS "potasio", NULL::double precision AS "sodio", NULL::double precision AS "amonio", NULL::double precision AS "magnesio", "observacion" AS "observaciones", CASE extract(MONTH FROM fechamonitoreo::date)::int WHEN 1 THEN 'ENERO' WHEN 2 THEN 'FEBRERO' WHEN 3 THEN 'MARZO' WHEN 4 THEN 'ABRIL' WHEN 5 THEN 'MAYO' WHEN 6 THEN 'JUNIO' WHEN 7 THEN 'JULIO' WHEN 8 THEN 'AGOSTO' WHEN 9 THEN 'SETIEMBRE' WHEN 10 THEN 'OCTUBRE' WHEN 11 THEN 'NOVIEMBRE' WHEN 12 THEN 'DICIEMBRE' END || ' ' || extract(YEAR FROM fechamonitoreo::date)::int AS campana, 'calidad agua' AS tipo
FROM calidadaguasuperficial2022.monitoreosuperficialjunio WHERE (fechamonitoreo IS NOT NULL OR cooreste IS NOT NULL OR coornorte IS NOT NULL OR ce IS NOT NULL OR ph IS NOT NULL OR turbidez IS NOT NULL)
UNION ALL
SELECT btrim(upper(coalesce(nullif(ubicacion,''),'(SIN NOMBRE)'))) || '|' || coalesce(cooreste::text,'') || '|' || coalesce(coornorte::text,'') AS clv, geom, cooreste, coornorte, zona, cota, departamento, provincia, distrito, ubicacion, descripcion, aaa, ala, uh, fechamonitoreo::date AS fechamonitoreo, fechamonitoreo::date + horamonitoreo::time AS horamonitoreo, orden, ce, ph, std, t, turbidez, nitratos, nitritos, cromohexavalente, cobre, manganeso, sulfatos, hierro, zinc, cloruros, coliformestotales, coliformestermotolerantes, escherichiacoli, "durezatotal", NULL::double precision AS "calcio", NULL::double precision AS "cloruro", NULL::double precision AS "potasio", NULL::double precision AS "sodio", NULL::double precision AS "amonio", NULL::double precision AS "magnesio", "observacion" AS "observaciones", CASE extract(MONTH FROM fechamonitoreo::date)::int WHEN 1 THEN 'ENERO' WHEN 2 THEN 'FEBRERO' WHEN 3 THEN 'MARZO' WHEN 4 THEN 'ABRIL' WHEN 5 THEN 'MAYO' WHEN 6 THEN 'JUNIO' WHEN 7 THEN 'JULIO' WHEN 8 THEN 'AGOSTO' WHEN 9 THEN 'SETIEMBRE' WHEN 10 THEN 'OCTUBRE' WHEN 11 THEN 'NOVIEMBRE' WHEN 12 THEN 'DICIEMBRE' END || ' ' || extract(YEAR FROM fechamonitoreo::date)::int AS campana, 'calidad agua' AS tipo
FROM calidadaguasuperficial2022.monitoreosuperficialnoviembre WHERE (fechamonitoreo IS NOT NULL OR cooreste IS NOT NULL OR coornorte IS NOT NULL OR ce IS NOT NULL OR ph IS NOT NULL OR turbidez IS NOT NULL)
UNION ALL
SELECT btrim(upper(coalesce(nullif(ubicacion,''),'(SIN NOMBRE)'))) || '|' || coalesce(cooreste::text,'') || '|' || coalesce(coornorte::text,'') AS clv, geom, cooreste, coornorte, zona, cota, departamento, provincia, distrito, ubicacion, descripcion, aaa, ala, uh, fechamonitoreo::date AS fechamonitoreo, fechamonitoreo::date + horamonitoreo::time AS horamonitoreo, orden, ce, ph, std, t, turbidez, nitratos, nitritos, cromohexavalente, cobre, manganeso, sulfatos, hierro, zinc, cloruros, coliformestotales, coliformestermotolerantes, escherichiacoli, "durezatotal", NULL::double precision AS "calcio", NULL::double precision AS "cloruro", NULL::double precision AS "potasio", NULL::double precision AS "sodio", NULL::double precision AS "amonio", NULL::double precision AS "magnesio", "observacion" AS "observaciones", CASE extract(MONTH FROM fechamonitoreo::date)::int WHEN 1 THEN 'ENERO' WHEN 2 THEN 'FEBRERO' WHEN 3 THEN 'MARZO' WHEN 4 THEN 'ABRIL' WHEN 5 THEN 'MAYO' WHEN 6 THEN 'JUNIO' WHEN 7 THEN 'JULIO' WHEN 8 THEN 'AGOSTO' WHEN 9 THEN 'SETIEMBRE' WHEN 10 THEN 'OCTUBRE' WHEN 11 THEN 'NOVIEMBRE' WHEN 12 THEN 'DICIEMBRE' END || ' ' || extract(YEAR FROM fechamonitoreo::date)::int AS campana, 'calidad agua' AS tipo
FROM calidadaguasuperficial2022.monitoreosuperficialsetiembre WHERE (fechamonitoreo IS NOT NULL OR cooreste IS NOT NULL OR coornorte IS NOT NULL OR ce IS NOT NULL OR ph IS NOT NULL OR turbidez IS NOT NULL)
UNION ALL
SELECT btrim(upper(coalesce(nullif(ubicacion,''),'(SIN NOMBRE)'))) || '|' || coalesce(cooreste::text,'') || '|' || coalesce(coornorte::text,'') AS clv, geom, cooreste, coornorte, zona, cota, departamento, provincia, distrito, ubicacion, descripcion, aaa, ala, uh, fechamonitoreo::date AS fechamonitoreo, fechamonitoreo::date + horamonitoreo::time AS horamonitoreo, orden, ce, ph, std, t, turbidez, nitratos, nitritos, cromohexavalente, cobre, manganeso, sulfatos, hierro, zinc, cloruros, coliformestotales, coliformestermotolerantes, escherichiacoli, "durezatotal", NULL::double precision AS "calcio", NULL::double precision AS "cloruro", NULL::double precision AS "potasio", NULL::double precision AS "sodio", NULL::double precision AS "amonio", NULL::double precision AS "magnesio", "observacion" AS "observaciones", CASE extract(MONTH FROM fechamonitoreo::date)::int WHEN 1 THEN 'ENERO' WHEN 2 THEN 'FEBRERO' WHEN 3 THEN 'MARZO' WHEN 4 THEN 'ABRIL' WHEN 5 THEN 'MAYO' WHEN 6 THEN 'JUNIO' WHEN 7 THEN 'JULIO' WHEN 8 THEN 'AGOSTO' WHEN 9 THEN 'SETIEMBRE' WHEN 10 THEN 'OCTUBRE' WHEN 11 THEN 'NOVIEMBRE' WHEN 12 THEN 'DICIEMBRE' END || ' ' || extract(YEAR FROM fechamonitoreo::date)::int AS campana, 'calidad agua' AS tipo
FROM calidadaguasuperficial2023.monitoreosuperficialagosto WHERE (fechamonitoreo IS NOT NULL OR cooreste IS NOT NULL OR coornorte IS NOT NULL OR ce IS NOT NULL OR ph IS NOT NULL OR turbidez IS NOT NULL)
UNION ALL
SELECT btrim(upper(coalesce(nullif(ubicacion,''),'(SIN NOMBRE)'))) || '|' || coalesce(cooreste::text,'') || '|' || coalesce(coornorte::text,'') AS clv, geom, cooreste, coornorte, zona, cota, departamento, provincia, distrito, ubicacion, descripcion, aaa, ala, uh, fechamonitoreo::date AS fechamonitoreo, fechamonitoreo::date + horamonitoreo::time AS horamonitoreo, orden, ce, ph, std, t, turbidez, nitratos, nitritos, cromohexavalente, cobre, manganeso, sulfatos, hierro, zinc, cloruros, coliformestotales, coliformestermotolerantes, escherichiacoli, "durezatotal", NULL::double precision AS "calcio", NULL::double precision AS "cloruro", NULL::double precision AS "potasio", NULL::double precision AS "sodio", NULL::double precision AS "amonio", NULL::double precision AS "magnesio", "observacion" AS "observaciones", CASE extract(MONTH FROM fechamonitoreo::date)::int WHEN 1 THEN 'ENERO' WHEN 2 THEN 'FEBRERO' WHEN 3 THEN 'MARZO' WHEN 4 THEN 'ABRIL' WHEN 5 THEN 'MAYO' WHEN 6 THEN 'JUNIO' WHEN 7 THEN 'JULIO' WHEN 8 THEN 'AGOSTO' WHEN 9 THEN 'SETIEMBRE' WHEN 10 THEN 'OCTUBRE' WHEN 11 THEN 'NOVIEMBRE' WHEN 12 THEN 'DICIEMBRE' END || ' ' || extract(YEAR FROM fechamonitoreo::date)::int AS campana, 'calidad agua' AS tipo
FROM calidadaguasuperficial2023.monitoreosuperficialdiciembre WHERE (fechamonitoreo IS NOT NULL OR cooreste IS NOT NULL OR coornorte IS NOT NULL OR ce IS NOT NULL OR ph IS NOT NULL OR turbidez IS NOT NULL)
UNION ALL
SELECT btrim(upper(coalesce(nullif(ubicacion,''),'(SIN NOMBRE)'))) || '|' || coalesce(cooreste::text,'') || '|' || coalesce(coornorte::text,'') AS clv, geom, cooreste, coornorte, zona, cota, departamento, provincia, distrito, ubicacion, descripcion, aaa, ala, uh, fechamonitoreo::date AS fechamonitoreo, fechamonitoreo::date + horamonitoreo::time AS horamonitoreo, orden, ce, ph, std, t, turbidez, nitratos, nitritos, cromohexavalente, cobre, manganeso, sulfatos, hierro, zinc, cloruros, coliformestotales, coliformestermotolerantes, escherichiacoli, "durezatotal", NULL::double precision AS "calcio", NULL::double precision AS "cloruro", NULL::double precision AS "potasio", NULL::double precision AS "sodio", NULL::double precision AS "amonio", NULL::double precision AS "magnesio", "observacion" AS "observaciones", CASE extract(MONTH FROM fechamonitoreo::date)::int WHEN 1 THEN 'ENERO' WHEN 2 THEN 'FEBRERO' WHEN 3 THEN 'MARZO' WHEN 4 THEN 'ABRIL' WHEN 5 THEN 'MAYO' WHEN 6 THEN 'JUNIO' WHEN 7 THEN 'JULIO' WHEN 8 THEN 'AGOSTO' WHEN 9 THEN 'SETIEMBRE' WHEN 10 THEN 'OCTUBRE' WHEN 11 THEN 'NOVIEMBRE' WHEN 12 THEN 'DICIEMBRE' END || ' ' || extract(YEAR FROM fechamonitoreo::date)::int AS campana, 'calidad agua' AS tipo
FROM calidadaguasuperficial2023.monitoreosuperficialmayo WHERE (fechamonitoreo IS NOT NULL OR cooreste IS NOT NULL OR coornorte IS NOT NULL OR ce IS NOT NULL OR ph IS NOT NULL OR turbidez IS NOT NULL)
UNION ALL
SELECT btrim(upper(coalesce(nullif(ubicacion,''),'(SIN NOMBRE)'))) || '|' || coalesce(cooreste::text,'') || '|' || coalesce(coornorte::text,'') AS clv, geom, cooreste, coornorte, zona, cota, departamento, provincia, distrito, ubicacion, descripcion, aaa, ala, uh, fechamonitoreo::date AS fechamonitoreo, fechamonitoreo::date + horamonitoreo::time AS horamonitoreo, orden, ce, ph, std, t, turbidez, nitratos, nitritos, cromohexavalente, cobre, manganeso, sulfatos, hierro, zinc, cloruros, coliformestotales, coliformestermotolerantes, escherichiacoli, "durezatotal", NULL::double precision AS "calcio", NULL::double precision AS "cloruro", NULL::double precision AS "potasio", NULL::double precision AS "sodio", NULL::double precision AS "amonio", NULL::double precision AS "magnesio", "observacion" AS "observaciones", CASE extract(MONTH FROM fechamonitoreo::date)::int WHEN 1 THEN 'ENERO' WHEN 2 THEN 'FEBRERO' WHEN 3 THEN 'MARZO' WHEN 4 THEN 'ABRIL' WHEN 5 THEN 'MAYO' WHEN 6 THEN 'JUNIO' WHEN 7 THEN 'JULIO' WHEN 8 THEN 'AGOSTO' WHEN 9 THEN 'SETIEMBRE' WHEN 10 THEN 'OCTUBRE' WHEN 11 THEN 'NOVIEMBRE' WHEN 12 THEN 'DICIEMBRE' END || ' ' || extract(YEAR FROM fechamonitoreo::date)::int AS campana, 'calidad agua' AS tipo
FROM calidadaguasuperficial2023.monitoreosuperficialoctubre WHERE (fechamonitoreo IS NOT NULL OR cooreste IS NOT NULL OR coornorte IS NOT NULL OR ce IS NOT NULL OR ph IS NOT NULL OR turbidez IS NOT NULL)
UNION ALL
SELECT btrim(upper(coalesce(nullif(ubicacion,''),'(SIN NOMBRE)'))) || '|' || coalesce(cooreste::text,'') || '|' || coalesce(coornorte::text,'') AS clv, geom, cooreste, coornorte, zona, cota, departamento, provincia, distrito, ubicacion, descripcion, aaa, ala, uh, fechamonitoreo::date AS fechamonitoreo, fechamonitoreo::date + horamonitoreo::time AS horamonitoreo, orden, ce, ph, std, t, turbidez, nitratos, nitritos, cromohexavalente, cobre, manganeso, sulfatos, hierro, zinc, cloruros, coliformestotales, coliformestermotolerantes, escherichiacoli, "durezatotal", "calcio", "cloruro", "potasio", "sodio", "amonio", "magnesio", "observacion" AS "observaciones", CASE extract(MONTH FROM fechamonitoreo::date)::int WHEN 1 THEN 'ENERO' WHEN 2 THEN 'FEBRERO' WHEN 3 THEN 'MARZO' WHEN 4 THEN 'ABRIL' WHEN 5 THEN 'MAYO' WHEN 6 THEN 'JUNIO' WHEN 7 THEN 'JULIO' WHEN 8 THEN 'AGOSTO' WHEN 9 THEN 'SETIEMBRE' WHEN 10 THEN 'OCTUBRE' WHEN 11 THEN 'NOVIEMBRE' WHEN 12 THEN 'DICIEMBRE' END || ' ' || extract(YEAR FROM fechamonitoreo::date)::int AS campana, 'calidad agua' AS tipo
FROM calidadaguasuperficial2024.monitoreosuperficialjunio WHERE (fechamonitoreo IS NOT NULL OR cooreste IS NOT NULL OR coornorte IS NOT NULL OR ce IS NOT NULL OR ph IS NOT NULL OR turbidez IS NOT NULL)
UNION ALL
SELECT btrim(upper(coalesce(nullif(ubicacion,''),'(SIN NOMBRE)'))) || '|' || coalesce(cooreste::text,'') || '|' || coalesce(coornorte::text,'') AS clv, geom, cooreste, coornorte, zona, cota, departamento, provincia, distrito, ubicacion, descripcion, aaa, ala, uh, fechamonitoreo::date AS fechamonitoreo, fechamonitoreo::date + horamonitoreo::time AS horamonitoreo, orden, ce, ph, std, t, turbidez, nitratos, nitritos, cromohexavalente, cobre, manganeso, sulfatos, hierro, zinc, cloruros, coliformestotales, coliformestermotolerantes, escherichiacoli, "durezatotal", "calcio", "cloruro", "potasio", "sodio", "amonio", "magnesio", "observacion" AS "observaciones", CASE extract(MONTH FROM fechamonitoreo::date)::int WHEN 1 THEN 'ENERO' WHEN 2 THEN 'FEBRERO' WHEN 3 THEN 'MARZO' WHEN 4 THEN 'ABRIL' WHEN 5 THEN 'MAYO' WHEN 6 THEN 'JUNIO' WHEN 7 THEN 'JULIO' WHEN 8 THEN 'AGOSTO' WHEN 9 THEN 'SETIEMBRE' WHEN 10 THEN 'OCTUBRE' WHEN 11 THEN 'NOVIEMBRE' WHEN 12 THEN 'DICIEMBRE' END || ' ' || extract(YEAR FROM fechamonitoreo::date)::int AS campana, 'calidad agua' AS tipo
FROM calidadaguasuperficial2024.monitoreosuperficialnoviembre WHERE (fechamonitoreo IS NOT NULL OR cooreste IS NOT NULL OR coornorte IS NOT NULL OR ce IS NOT NULL OR ph IS NOT NULL OR turbidez IS NOT NULL)
UNION ALL
SELECT btrim(upper(coalesce(nullif(ubicacion,''),'(SIN NOMBRE)'))) || '|' || coalesce(cooreste::text,'') || '|' || coalesce(coornorte::text,'') AS clv, geom, cooreste, coornorte, zona, cota, departamento, provincia, distrito, ubicacion, descripcion, aaa, ala, uh, fechamonitoreo::date AS fechamonitoreo, fechamonitoreo::date + horamonitoreo::time AS horamonitoreo, orden, ce, ph, std, t, turbidez, nitratos, nitritos, cromohexavalente, cobre, manganeso, sulfatos, hierro, zinc, cloruros, coliformestotales, coliformestermotolerantes, escherichiacoli, "durezatotal", "calcio", "cloruro", "potasio", "sodio", "amonio", "magnesio", "observaciones", CASE extract(MONTH FROM fechamonitoreo::date)::int WHEN 1 THEN 'ENERO' WHEN 2 THEN 'FEBRERO' WHEN 3 THEN 'MARZO' WHEN 4 THEN 'ABRIL' WHEN 5 THEN 'MAYO' WHEN 6 THEN 'JUNIO' WHEN 7 THEN 'JULIO' WHEN 8 THEN 'AGOSTO' WHEN 9 THEN 'SETIEMBRE' WHEN 10 THEN 'OCTUBRE' WHEN 11 THEN 'NOVIEMBRE' WHEN 12 THEN 'DICIEMBRE' END || ' ' || extract(YEAR FROM fechamonitoreo::date)::int AS campana, 'calidad agua' AS tipo
FROM calidadaguasuperficial2025.monitoreosuperficialdiciembre WHERE (fechamonitoreo IS NOT NULL OR cooreste IS NOT NULL OR coornorte IS NOT NULL OR ce IS NOT NULL OR ph IS NOT NULL OR turbidez IS NOT NULL)
UNION ALL
SELECT btrim(upper(coalesce(nullif(ubicacion,''),'(SIN NOMBRE)'))) || '|' || coalesce(cooreste::text,'') || '|' || coalesce(coornorte::text,'') AS clv, geom, cooreste, coornorte, zona, cota, departamento, provincia, distrito, ubicacion, descripcion, aaa, ala, uh, fechamonitoreo::date AS fechamonitoreo, fechamonitoreo::date + horamonitoreo::time AS horamonitoreo, orden, ce, ph, std, t, turbidez, nitratos, nitritos, cromohexavalente, cobre, manganeso, sulfatos, hierro, zinc, cloruros, coliformestotales, coliformestermotolerantes, escherichiacoli, "durezatotal", "calcio", "cloruro", "potasio", "sodio", "amonio", "magnesio", "observaciones", CASE extract(MONTH FROM fechamonitoreo::date)::int WHEN 1 THEN 'ENERO' WHEN 2 THEN 'FEBRERO' WHEN 3 THEN 'MARZO' WHEN 4 THEN 'ABRIL' WHEN 5 THEN 'MAYO' WHEN 6 THEN 'JUNIO' WHEN 7 THEN 'JULIO' WHEN 8 THEN 'AGOSTO' WHEN 9 THEN 'SETIEMBRE' WHEN 10 THEN 'OCTUBRE' WHEN 11 THEN 'NOVIEMBRE' WHEN 12 THEN 'DICIEMBRE' END || ' ' || extract(YEAR FROM fechamonitoreo::date)::int AS campana, 'calidad agua' AS tipo
FROM calidadaguasuperficial2025.monitoreosuperficialjulio WHERE (fechamonitoreo IS NOT NULL OR cooreste IS NOT NULL OR coornorte IS NOT NULL OR ce IS NOT NULL OR ph IS NOT NULL OR turbidez IS NOT NULL)
UNION ALL
SELECT btrim(upper(coalesce(nullif(ubicacion,''),'(SIN NOMBRE)'))) || '|' || coalesce(cooreste::text,'') || '|' || coalesce(coornorte::text,'') AS clv, geom, cooreste, coornorte, zona, cota, departamento, provincia, distrito, ubicacion, descripcion, aaa, ala, uh, fechamonitoreo::date AS fechamonitoreo, fechamonitoreo::date + horamonitoreo::time AS horamonitoreo, orden, ce, ph, std, t, turbidez, nitratos, nitritos, cromohexavalente, cobre, manganeso, sulfatos, hierro, zinc, cloruros, coliformestotales, coliformestermotolerantes, escherichiacoli, "durezatotal", "calcio", "cloruro", "potasio", "sodio", "amonio", "magnesio", "observaciones", CASE extract(MONTH FROM fechamonitoreo::date)::int WHEN 1 THEN 'ENERO' WHEN 2 THEN 'FEBRERO' WHEN 3 THEN 'MARZO' WHEN 4 THEN 'ABRIL' WHEN 5 THEN 'MAYO' WHEN 6 THEN 'JUNIO' WHEN 7 THEN 'JULIO' WHEN 8 THEN 'AGOSTO' WHEN 9 THEN 'SETIEMBRE' WHEN 10 THEN 'OCTUBRE' WHEN 11 THEN 'NOVIEMBRE' WHEN 12 THEN 'DICIEMBRE' END || ' ' || extract(YEAR FROM fechamonitoreo::date)::int AS campana, 'calidad agua' AS tipo
FROM calidadaguasuperficial2025.monitoreosuperficialmarzo WHERE (fechamonitoreo IS NOT NULL OR cooreste IS NOT NULL OR coornorte IS NOT NULL OR ce IS NOT NULL OR ph IS NOT NULL OR turbidez IS NOT NULL)
UNION ALL
SELECT btrim(upper(coalesce(nullif(ubicacion,''),'(SIN NOMBRE)'))) || '|' || coalesce(cooreste::text,'') || '|' || coalesce(coornorte::text,'') AS clv, geom, cooreste, coornorte, zona, cota, departamento, provincia, distrito, ubicacion, descripcion, aaa, ala, uh, fechamonitoreo::date AS fechamonitoreo, fechamonitoreo::date + horamonitoreo::time AS horamonitoreo, orden, ce, ph, std, t, turbidez, nitratos, nitritos, cromohexavalente, cobre, manganeso, sulfatos, hierro, zinc, cloruros, coliformestotales, coliformestermotolerantes, escherichiacoli, "durezatotal", "calcio", "cloruro", "potasio", "sodio", "amonio", "magnesio", "observaciones", CASE extract(MONTH FROM fechamonitoreo::date)::int WHEN 1 THEN 'ENERO' WHEN 2 THEN 'FEBRERO' WHEN 3 THEN 'MARZO' WHEN 4 THEN 'ABRIL' WHEN 5 THEN 'MAYO' WHEN 6 THEN 'JUNIO' WHEN 7 THEN 'JULIO' WHEN 8 THEN 'AGOSTO' WHEN 9 THEN 'SETIEMBRE' WHEN 10 THEN 'OCTUBRE' WHEN 11 THEN 'NOVIEMBRE' WHEN 12 THEN 'DICIEMBRE' END || ' ' || extract(YEAR FROM fechamonitoreo::date)::int AS campana, 'calidad agua' AS tipo
FROM calidadaguasuperficial2025.monitoreosuperficialnoviembre WHERE (fechamonitoreo IS NOT NULL OR cooreste IS NOT NULL OR coornorte IS NOT NULL OR ce IS NOT NULL OR ph IS NOT NULL OR turbidez IS NOT NULL)
UNION ALL
SELECT btrim(upper(coalesce(nullif(ubicacion,''),'(SIN NOMBRE)'))) || '|' || coalesce(cooreste::text,'') || '|' || coalesce(coornorte::text,'') AS clv, geom, cooreste, coornorte, zona, cota, departamento, provincia, distrito, ubicacion, descripcion, aaa, ala, uh, fechamonitoreo::date AS fechamonitoreo, fechamonitoreo::date + horamonitoreo::time AS horamonitoreo, orden, ce, ph, std, t, turbidez, nitratos, nitritos, cromohexavalente, cobre, manganeso, sulfatos, hierro, zinc, cloruros, coliformestotales, coliformestermotolerantes, escherichiacoli, "durezatotal", "calcio", "cloruro", "potasio", "sodio", "amonio", "magnesio", "observaciones", CASE extract(MONTH FROM fechamonitoreo::date)::int WHEN 1 THEN 'ENERO' WHEN 2 THEN 'FEBRERO' WHEN 3 THEN 'MARZO' WHEN 4 THEN 'ABRIL' WHEN 5 THEN 'MAYO' WHEN 6 THEN 'JUNIO' WHEN 7 THEN 'JULIO' WHEN 8 THEN 'AGOSTO' WHEN 9 THEN 'SETIEMBRE' WHEN 10 THEN 'OCTUBRE' WHEN 11 THEN 'NOVIEMBRE' WHEN 12 THEN 'DICIEMBRE' END || ' ' || extract(YEAR FROM fechamonitoreo::date)::int AS campana, 'calidad agua' AS tipo
FROM calidadaguasuperficial2026.monitoreosuperficialagosto WHERE (fechamonitoreo IS NOT NULL OR cooreste IS NOT NULL OR coornorte IS NOT NULL OR ce IS NOT NULL OR ph IS NOT NULL OR turbidez IS NOT NULL)
UNION ALL
SELECT btrim(upper(coalesce(nullif(ubicacion,''),'(SIN NOMBRE)'))) || '|' || coalesce(cooreste::text,'') || '|' || coalesce(coornorte::text,'') AS clv, geom, cooreste, coornorte, zona, cota, departamento, provincia, distrito, ubicacion, descripcion, aaa, ala, uh, fechamonitoreo::date AS fechamonitoreo, fechamonitoreo::date + horamonitoreo::time AS horamonitoreo, orden, ce, ph, std, t, turbidez, nitratos, nitritos, cromohexavalente, cobre, manganeso, sulfatos, hierro, zinc, cloruros, coliformestotales, coliformestermotolerantes, escherichiacoli, "durezatotal", "calcio", "cloruro", "potasio", "sodio", "amonio", "magnesio", "observaciones", CASE extract(MONTH FROM fechamonitoreo::date)::int WHEN 1 THEN 'ENERO' WHEN 2 THEN 'FEBRERO' WHEN 3 THEN 'MARZO' WHEN 4 THEN 'ABRIL' WHEN 5 THEN 'MAYO' WHEN 6 THEN 'JUNIO' WHEN 7 THEN 'JULIO' WHEN 8 THEN 'AGOSTO' WHEN 9 THEN 'SETIEMBRE' WHEN 10 THEN 'OCTUBRE' WHEN 11 THEN 'NOVIEMBRE' WHEN 12 THEN 'DICIEMBRE' END || ' ' || extract(YEAR FROM fechamonitoreo::date)::int AS campana, 'calidad agua' AS tipo
FROM calidadaguasuperficial2026.monitoreosuperficialmarzo WHERE (fechamonitoreo IS NOT NULL OR cooreste IS NOT NULL OR coornorte IS NOT NULL OR ce IS NOT NULL OR ph IS NOT NULL OR turbidez IS NOT NULL)
),
dedup AS (
    SELECT DISTINCT ON (clv) *
    FROM un
    WHERE clv IS NOT NULL
    ORDER BY clv,
        (cooreste IS NOT NULL) DESC,
        (fechamonitoreo IS NOT NULL) DESC,
        fechamonitoreo
),
ordered AS (
    SELECT *, row_number() OVER (ORDER BY clv) AS rn FROM dedup
)
INSERT INTO hidrologia.calidad_catastro
    (id_calidad, geom, cooreste, coornorte, zona, cota, departamento, provincia, distrito,
     ubicacion, descripcion, aaa, ala, uh, fechainventario, observaciones)
SELECT 'CAL-' || lpad(rn::text, 3, '0'),
       geom, cooreste, coornorte, zona, cota, departamento, provincia, distrito,
       ubicacion, descripcion, aaa, ala, uh, fechamonitoreo, observaciones
FROM ordered;
