-- 03_migracion.sql - Migra las mediciones historicas de calidad (drenes + superficial, 2022-2026)
--   * pozos_monitoreo:        in-situ por medicion (ce, ph, std, t) + campana, tipo=drene/calidad agua
--   * calidad_agua_laboratorio: parametros extendidos por medicion, enlazados por id_medicion, con tipo
--   Los puntos se resuelven contra drenes_catastro / calidad_catastro por ubicacion+coordenadas.
\set ON_ERROR_STOP on

BEGIN;

DO $$
DECLARE
    r       RECORD;
    newmed  INTEGER;
    n_th   INTEGER := 0;
BEGIN
    FOR r IN
        SELECT u.*,
               CASE WHEN u.tipo = 'drene' THEN d.id_dren ELSE c.id_calidad END AS id_catalogo
        FROM ( SELECT btrim(upper(coalesce(nullif(ubicacion,''),'(SIN NOMBRE)'))) || '|' || coalesce(cooreste::text,'') || '|' || coalesce(coornorte::text,'') AS clv, geom, cooreste, coornorte, zona, cota, departamento, provincia, distrito, ubicacion, descripcion, aaa, ala, uh, fechamonitoreo::date AS fechamonitoreo, fechamonitoreo::date + horamonitoreo::time AS horamonitoreo, orden, ce, ph, std, t, turbidez, nitratos, nitritos, cromohexavalente, cobre, manganeso, sulfatos, hierro, zinc, cloruros, coliformestotales, coliformestermotolerantes, escherichiacoli, "dureza" AS "durezatotal", NULL::double precision AS "calcio", NULL::double precision AS "cloruro", NULL::double precision AS "potasio", NULL::double precision AS "sodio", NULL::double precision AS "amonio", NULL::double precision AS "magnesio", "observacion" AS "observaciones", CASE extract(MONTH FROM fechamonitoreo::date)::int WHEN 1 THEN 'ENERO' WHEN 2 THEN 'FEBRERO' WHEN 3 THEN 'MARZO' WHEN 4 THEN 'ABRIL' WHEN 5 THEN 'MAYO' WHEN 6 THEN 'JUNIO' WHEN 7 THEN 'JULIO' WHEN 8 THEN 'AGOSTO' WHEN 9 THEN 'SETIEMBRE' WHEN 10 THEN 'OCTUBRE' WHEN 11 THEN 'NOVIEMBRE' WHEN 12 THEN 'DICIEMBRE' END || ' ' || extract(YEAR FROM fechamonitoreo::date)::int AS campana, 'drene' AS tipo
FROM calidadaguadrenada2022.monitoreodrenajeabril WHERE (fechamonitoreo IS NOT NULL OR cooreste IS NOT NULL OR coornorte IS NOT NULL OR ce IS NOT NULL OR ph IS NOT NULL OR turbidez IS NOT NULL)
UNION ALL
SELECT btrim(upper(coalesce(nullif(ubicacion,''),'(SIN NOMBRE)'))) || '|' || coalesce(cooreste::text,'') || '|' || coalesce(coornorte::text,'') AS clv, geom, cooreste, coornorte, zona, cota, departamento, provincia, distrito, ubicacion, descripcion, aaa, ala, uh, fechamonitoreo::date AS fechamonitoreo, fechamonitoreo::date + horamonitoreo::time AS horamonitoreo, orden, ce, ph, std, t, turbidez, nitratos, nitritos, cromohexavalente, cobre, manganeso, sulfatos, hierro, zinc, cloruros, coliformestotales, coliformestermotolerantes, escherichiacoli, "dureza" AS "durezatotal", NULL::double precision AS "calcio", NULL::double precision AS "cloruro", NULL::double precision AS "potasio", NULL::double precision AS "sodio", NULL::double precision AS "amonio", NULL::double precision AS "magnesio", "observacion" AS "observaciones", CASE extract(MONTH FROM fechamonitoreo::date)::int WHEN 1 THEN 'ENERO' WHEN 2 THEN 'FEBRERO' WHEN 3 THEN 'MARZO' WHEN 4 THEN 'ABRIL' WHEN 5 THEN 'MAYO' WHEN 6 THEN 'JUNIO' WHEN 7 THEN 'JULIO' WHEN 8 THEN 'AGOSTO' WHEN 9 THEN 'SETIEMBRE' WHEN 10 THEN 'OCTUBRE' WHEN 11 THEN 'NOVIEMBRE' WHEN 12 THEN 'DICIEMBRE' END || ' ' || extract(YEAR FROM fechamonitoreo::date)::int AS campana, 'drene' AS tipo
FROM calidadaguadrenada2022.monitoreodrenajeagosto WHERE (fechamonitoreo IS NOT NULL OR cooreste IS NOT NULL OR coornorte IS NOT NULL OR ce IS NOT NULL OR ph IS NOT NULL OR turbidez IS NOT NULL)
UNION ALL
SELECT btrim(upper(coalesce(nullif(ubicacion,''),'(SIN NOMBRE)'))) || '|' || coalesce(cooreste::text,'') || '|' || coalesce(coornorte::text,'') AS clv, geom, cooreste, coornorte, zona, cota, departamento, provincia, distrito, ubicacion, descripcion, aaa, ala, uh, fechamonitoreo::date AS fechamonitoreo, fechamonitoreo::date + horamonitoreo::time AS horamonitoreo, orden, ce, ph, std, t, turbidez, nitratos, nitritos, cromohexavalente, cobre, manganeso, sulfatos, hierro, zinc, cloruros, coliformestotales, coliformestermotolerantes, escherichiacoli, "dureza" AS "durezatotal", NULL::double precision AS "calcio", NULL::double precision AS "cloruro", NULL::double precision AS "potasio", NULL::double precision AS "sodio", NULL::double precision AS "amonio", NULL::double precision AS "magnesio", "observacion" AS "observaciones", CASE extract(MONTH FROM fechamonitoreo::date)::int WHEN 1 THEN 'ENERO' WHEN 2 THEN 'FEBRERO' WHEN 3 THEN 'MARZO' WHEN 4 THEN 'ABRIL' WHEN 5 THEN 'MAYO' WHEN 6 THEN 'JUNIO' WHEN 7 THEN 'JULIO' WHEN 8 THEN 'AGOSTO' WHEN 9 THEN 'SETIEMBRE' WHEN 10 THEN 'OCTUBRE' WHEN 11 THEN 'NOVIEMBRE' WHEN 12 THEN 'DICIEMBRE' END || ' ' || extract(YEAR FROM fechamonitoreo::date)::int AS campana, 'drene' AS tipo
FROM calidadaguadrenada2022.monitoreodrenajediciembre WHERE (fechamonitoreo IS NOT NULL OR cooreste IS NOT NULL OR coornorte IS NOT NULL OR ce IS NOT NULL OR ph IS NOT NULL OR turbidez IS NOT NULL)
UNION ALL
SELECT btrim(upper(coalesce(nullif(ubicacion,''),'(SIN NOMBRE)'))) || '|' || coalesce(cooreste::text,'') || '|' || coalesce(coornorte::text,'') AS clv, geom, cooreste, coornorte, zona, cota, departamento, provincia, distrito, ubicacion, descripcion, aaa, ala, uh, fechamonitoreo::date AS fechamonitoreo, fechamonitoreo::date + horamonitoreo::time AS horamonitoreo, orden, ce, ph, std, t, turbidez, nitratos, nitritos, cromohexavalente, cobre, manganeso, sulfatos, hierro, zinc, cloruros, coliformestotales, coliformestermotolerantes, escherichiacoli, "dureza" AS "durezatotal", NULL::double precision AS "calcio", NULL::double precision AS "cloruro", NULL::double precision AS "potasio", NULL::double precision AS "sodio", NULL::double precision AS "amonio", NULL::double precision AS "magnesio", "observacion" AS "observaciones", CASE extract(MONTH FROM fechamonitoreo::date)::int WHEN 1 THEN 'ENERO' WHEN 2 THEN 'FEBRERO' WHEN 3 THEN 'MARZO' WHEN 4 THEN 'ABRIL' WHEN 5 THEN 'MAYO' WHEN 6 THEN 'JUNIO' WHEN 7 THEN 'JULIO' WHEN 8 THEN 'AGOSTO' WHEN 9 THEN 'SETIEMBRE' WHEN 10 THEN 'OCTUBRE' WHEN 11 THEN 'NOVIEMBRE' WHEN 12 THEN 'DICIEMBRE' END || ' ' || extract(YEAR FROM fechamonitoreo::date)::int AS campana, 'drene' AS tipo
FROM calidadaguadrenada2022.monitoreodrenajejulio WHERE (fechamonitoreo IS NOT NULL OR cooreste IS NOT NULL OR coornorte IS NOT NULL OR ce IS NOT NULL OR ph IS NOT NULL OR turbidez IS NOT NULL)
UNION ALL
SELECT btrim(upper(coalesce(nullif(ubicacion,''),'(SIN NOMBRE)'))) || '|' || coalesce(cooreste::text,'') || '|' || coalesce(coornorte::text,'') AS clv, geom, cooreste, coornorte, zona, cota, departamento, provincia, distrito, ubicacion, descripcion, aaa, ala, uh, fechamonitoreo::date AS fechamonitoreo, fechamonitoreo::date + horamonitoreo::time AS horamonitoreo, orden, ce, ph, std, t, turbidez, nitratos, nitritos, cromohexavalente, cobre, manganeso, sulfatos, hierro, zinc, cloruros, coliformestotales, coliformestermotolerantes, escherichiacoli, "dureza" AS "durezatotal", NULL::double precision AS "calcio", NULL::double precision AS "cloruro", NULL::double precision AS "potasio", NULL::double precision AS "sodio", NULL::double precision AS "amonio", NULL::double precision AS "magnesio", "observacion" AS "observaciones", CASE extract(MONTH FROM fechamonitoreo::date)::int WHEN 1 THEN 'ENERO' WHEN 2 THEN 'FEBRERO' WHEN 3 THEN 'MARZO' WHEN 4 THEN 'ABRIL' WHEN 5 THEN 'MAYO' WHEN 6 THEN 'JUNIO' WHEN 7 THEN 'JULIO' WHEN 8 THEN 'AGOSTO' WHEN 9 THEN 'SETIEMBRE' WHEN 10 THEN 'OCTUBRE' WHEN 11 THEN 'NOVIEMBRE' WHEN 12 THEN 'DICIEMBRE' END || ' ' || extract(YEAR FROM fechamonitoreo::date)::int AS campana, 'drene' AS tipo
FROM calidadaguadrenada2022.monitoreodrenajejunio WHERE (fechamonitoreo IS NOT NULL OR cooreste IS NOT NULL OR coornorte IS NOT NULL OR ce IS NOT NULL OR ph IS NOT NULL OR turbidez IS NOT NULL)
UNION ALL
SELECT btrim(upper(coalesce(nullif(ubicacion,''),'(SIN NOMBRE)'))) || '|' || coalesce(cooreste::text,'') || '|' || coalesce(coornorte::text,'') AS clv, geom, cooreste, coornorte, zona, cota, departamento, provincia, distrito, ubicacion, descripcion, aaa, ala, uh, fechamonitoreo::date AS fechamonitoreo, fechamonitoreo::date + horamonitoreo::time AS horamonitoreo, orden, ce, ph, std, t, turbidez, nitratos, nitritos, cromohexavalente, cobre, manganeso, sulfatos, hierro, zinc, cloruros, coliformestotales, coliformestermotolerantes, escherichiacoli, "dureza" AS "durezatotal", NULL::double precision AS "calcio", NULL::double precision AS "cloruro", NULL::double precision AS "potasio", NULL::double precision AS "sodio", NULL::double precision AS "amonio", NULL::double precision AS "magnesio", "observacion" AS "observaciones", CASE extract(MONTH FROM fechamonitoreo::date)::int WHEN 1 THEN 'ENERO' WHEN 2 THEN 'FEBRERO' WHEN 3 THEN 'MARZO' WHEN 4 THEN 'ABRIL' WHEN 5 THEN 'MAYO' WHEN 6 THEN 'JUNIO' WHEN 7 THEN 'JULIO' WHEN 8 THEN 'AGOSTO' WHEN 9 THEN 'SETIEMBRE' WHEN 10 THEN 'OCTUBRE' WHEN 11 THEN 'NOVIEMBRE' WHEN 12 THEN 'DICIEMBRE' END || ' ' || extract(YEAR FROM fechamonitoreo::date)::int AS campana, 'drene' AS tipo
FROM calidadaguadrenada2022.monitoreodrenajemarzo WHERE (fechamonitoreo IS NOT NULL OR cooreste IS NOT NULL OR coornorte IS NOT NULL OR ce IS NOT NULL OR ph IS NOT NULL OR turbidez IS NOT NULL)
UNION ALL
SELECT btrim(upper(coalesce(nullif(ubicacion,''),'(SIN NOMBRE)'))) || '|' || coalesce(cooreste::text,'') || '|' || coalesce(coornorte::text,'') AS clv, geom, cooreste, coornorte, zona, cota, departamento, provincia, distrito, ubicacion, descripcion, aaa, ala, uh, fechamonitoreo::date AS fechamonitoreo, fechamonitoreo::date + horamonitoreo::time AS horamonitoreo, orden, ce, ph, std, t, turbidez, nitratos, nitritos, cromohexavalente, cobre, manganeso, sulfatos, hierro, zinc, cloruros, coliformestotales, coliformestermotolerantes, escherichiacoli, "dureza" AS "durezatotal", NULL::double precision AS "calcio", NULL::double precision AS "cloruro", NULL::double precision AS "potasio", NULL::double precision AS "sodio", NULL::double precision AS "amonio", NULL::double precision AS "magnesio", "observacion" AS "observaciones", CASE extract(MONTH FROM fechamonitoreo::date)::int WHEN 1 THEN 'ENERO' WHEN 2 THEN 'FEBRERO' WHEN 3 THEN 'MARZO' WHEN 4 THEN 'ABRIL' WHEN 5 THEN 'MAYO' WHEN 6 THEN 'JUNIO' WHEN 7 THEN 'JULIO' WHEN 8 THEN 'AGOSTO' WHEN 9 THEN 'SETIEMBRE' WHEN 10 THEN 'OCTUBRE' WHEN 11 THEN 'NOVIEMBRE' WHEN 12 THEN 'DICIEMBRE' END || ' ' || extract(YEAR FROM fechamonitoreo::date)::int AS campana, 'drene' AS tipo
FROM calidadaguadrenada2022.monitoreodrenajenoviembre WHERE (fechamonitoreo IS NOT NULL OR cooreste IS NOT NULL OR coornorte IS NOT NULL OR ce IS NOT NULL OR ph IS NOT NULL OR turbidez IS NOT NULL)
UNION ALL
SELECT btrim(upper(coalesce(nullif(ubicacion,''),'(SIN NOMBRE)'))) || '|' || coalesce(cooreste::text,'') || '|' || coalesce(coornorte::text,'') AS clv, geom, cooreste, coornorte, zona, cota, departamento, provincia, distrito, ubicacion, descripcion, aaa, ala, uh, fechamonitoreo::date AS fechamonitoreo, fechamonitoreo::date + horamonitoreo::time AS horamonitoreo, orden, ce, ph, std, t, turbidez, nitratos, nitritos, cromohexavalente, cobre, manganeso, sulfatos, hierro, zinc, cloruros, coliformestotales, coliformestermotolerantes, escherichiacoli, "dureza" AS "durezatotal", NULL::double precision AS "calcio", NULL::double precision AS "cloruro", NULL::double precision AS "potasio", NULL::double precision AS "sodio", NULL::double precision AS "amonio", NULL::double precision AS "magnesio", "observacion" AS "observaciones", CASE extract(MONTH FROM fechamonitoreo::date)::int WHEN 1 THEN 'ENERO' WHEN 2 THEN 'FEBRERO' WHEN 3 THEN 'MARZO' WHEN 4 THEN 'ABRIL' WHEN 5 THEN 'MAYO' WHEN 6 THEN 'JUNIO' WHEN 7 THEN 'JULIO' WHEN 8 THEN 'AGOSTO' WHEN 9 THEN 'SETIEMBRE' WHEN 10 THEN 'OCTUBRE' WHEN 11 THEN 'NOVIEMBRE' WHEN 12 THEN 'DICIEMBRE' END || ' ' || extract(YEAR FROM fechamonitoreo::date)::int AS campana, 'drene' AS tipo
FROM calidadaguadrenada2022.monitoreodrenajeoctubre WHERE (fechamonitoreo IS NOT NULL OR cooreste IS NOT NULL OR coornorte IS NOT NULL OR ce IS NOT NULL OR ph IS NOT NULL OR turbidez IS NOT NULL)
UNION ALL
SELECT btrim(upper(coalesce(nullif(ubicacion,''),'(SIN NOMBRE)'))) || '|' || coalesce(cooreste::text,'') || '|' || coalesce(coornorte::text,'') AS clv, geom, cooreste, coornorte, zona, cota, departamento, provincia, distrito, ubicacion, descripcion, aaa, ala, uh, fechamonitoreo::date AS fechamonitoreo, fechamonitoreo::date + horamonitoreo::time AS horamonitoreo, orden, ce, ph, std, t, turbidez, nitratos, nitritos, cromohexavalente, cobre, manganeso, sulfatos, hierro, zinc, cloruros, coliformestotales, coliformestermotolerantes, escherichiacoli, "dureza" AS "durezatotal", NULL::double precision AS "calcio", NULL::double precision AS "cloruro", NULL::double precision AS "potasio", NULL::double precision AS "sodio", NULL::double precision AS "amonio", NULL::double precision AS "magnesio", "observacion" AS "observaciones", CASE extract(MONTH FROM fechamonitoreo::date)::int WHEN 1 THEN 'ENERO' WHEN 2 THEN 'FEBRERO' WHEN 3 THEN 'MARZO' WHEN 4 THEN 'ABRIL' WHEN 5 THEN 'MAYO' WHEN 6 THEN 'JUNIO' WHEN 7 THEN 'JULIO' WHEN 8 THEN 'AGOSTO' WHEN 9 THEN 'SETIEMBRE' WHEN 10 THEN 'OCTUBRE' WHEN 11 THEN 'NOVIEMBRE' WHEN 12 THEN 'DICIEMBRE' END || ' ' || extract(YEAR FROM fechamonitoreo::date)::int AS campana, 'drene' AS tipo
FROM calidadaguadrenada2022.monitoreodrenajesetiembre WHERE (fechamonitoreo IS NOT NULL OR cooreste IS NOT NULL OR coornorte IS NOT NULL OR ce IS NOT NULL OR ph IS NOT NULL OR turbidez IS NOT NULL)
UNION ALL
SELECT btrim(upper(coalesce(nullif(ubicacion,''),'(SIN NOMBRE)'))) || '|' || coalesce(cooreste::text,'') || '|' || coalesce(coornorte::text,'') AS clv, geom, cooreste, coornorte, zona, cota, departamento, provincia, distrito, ubicacion, descripcion, aaa, ala, uh, fechamonitoreo::date AS fechamonitoreo, fechamonitoreo::date + horamonitoreo::time AS horamonitoreo, orden, ce, ph, std, t, turbidez, nitratos, nitritos, cromohexavalente, cobre, manganeso, sulfatos, hierro, zinc, cloruros, coliformestotales, coliformestermotolerantes, escherichiacoli, "dureza" AS "durezatotal", NULL::double precision AS "calcio", NULL::double precision AS "cloruro", NULL::double precision AS "potasio", NULL::double precision AS "sodio", NULL::double precision AS "amonio", NULL::double precision AS "magnesio", "observacion" AS "observaciones", CASE extract(MONTH FROM fechamonitoreo::date)::int WHEN 1 THEN 'ENERO' WHEN 2 THEN 'FEBRERO' WHEN 3 THEN 'MARZO' WHEN 4 THEN 'ABRIL' WHEN 5 THEN 'MAYO' WHEN 6 THEN 'JUNIO' WHEN 7 THEN 'JULIO' WHEN 8 THEN 'AGOSTO' WHEN 9 THEN 'SETIEMBRE' WHEN 10 THEN 'OCTUBRE' WHEN 11 THEN 'NOVIEMBRE' WHEN 12 THEN 'DICIEMBRE' END || ' ' || extract(YEAR FROM fechamonitoreo::date)::int AS campana, 'drene' AS tipo
FROM calidadaguadrenada2023.monitoreodrenajeabril WHERE (fechamonitoreo IS NOT NULL OR cooreste IS NOT NULL OR coornorte IS NOT NULL OR ce IS NOT NULL OR ph IS NOT NULL OR turbidez IS NOT NULL)
UNION ALL
SELECT btrim(upper(coalesce(nullif(ubicacion,''),'(SIN NOMBRE)'))) || '|' || coalesce(cooreste::text,'') || '|' || coalesce(coornorte::text,'') AS clv, geom, cooreste, coornorte, zona, cota, departamento, provincia, distrito, ubicacion, descripcion, aaa, ala, uh, fechamonitoreo::date AS fechamonitoreo, fechamonitoreo::date + horamonitoreo::time AS horamonitoreo, orden, ce, ph, std, t, turbidez, nitratos, nitritos, cromohexavalente, cobre, manganeso, sulfatos, hierro, zinc, cloruros, coliformestotales, coliformestermotolerantes, escherichiacoli, "dureza" AS "durezatotal", NULL::double precision AS "calcio", NULL::double precision AS "cloruro", NULL::double precision AS "potasio", NULL::double precision AS "sodio", NULL::double precision AS "amonio", NULL::double precision AS "magnesio", "observacion" AS "observaciones", CASE extract(MONTH FROM fechamonitoreo::date)::int WHEN 1 THEN 'ENERO' WHEN 2 THEN 'FEBRERO' WHEN 3 THEN 'MARZO' WHEN 4 THEN 'ABRIL' WHEN 5 THEN 'MAYO' WHEN 6 THEN 'JUNIO' WHEN 7 THEN 'JULIO' WHEN 8 THEN 'AGOSTO' WHEN 9 THEN 'SETIEMBRE' WHEN 10 THEN 'OCTUBRE' WHEN 11 THEN 'NOVIEMBRE' WHEN 12 THEN 'DICIEMBRE' END || ' ' || extract(YEAR FROM fechamonitoreo::date)::int AS campana, 'drene' AS tipo
FROM calidadaguadrenada2023.monitoreodrenajejulio WHERE (fechamonitoreo IS NOT NULL OR cooreste IS NOT NULL OR coornorte IS NOT NULL OR ce IS NOT NULL OR ph IS NOT NULL OR turbidez IS NOT NULL)
UNION ALL
SELECT btrim(upper(coalesce(nullif(ubicacion,''),'(SIN NOMBRE)'))) || '|' || coalesce(cooreste::text,'') || '|' || coalesce(coornorte::text,'') AS clv, geom, cooreste, coornorte, zona, cota, departamento, provincia, distrito, ubicacion, descripcion, aaa, ala, uh, fechamonitoreo::date AS fechamonitoreo, fechamonitoreo::date + horamonitoreo::time AS horamonitoreo, orden, ce, ph, std, t, turbidez, nitratos, nitritos, cromohexavalente, cobre, manganeso, sulfatos, hierro, zinc, cloruros, coliformestotales, coliformestermotolerantes, escherichiacoli, "dureza" AS "durezatotal", NULL::double precision AS "calcio", NULL::double precision AS "cloruro", NULL::double precision AS "potasio", NULL::double precision AS "sodio", NULL::double precision AS "amonio", NULL::double precision AS "magnesio", "observacion" AS "observaciones", CASE extract(MONTH FROM fechamonitoreo::date)::int WHEN 1 THEN 'ENERO' WHEN 2 THEN 'FEBRERO' WHEN 3 THEN 'MARZO' WHEN 4 THEN 'ABRIL' WHEN 5 THEN 'MAYO' WHEN 6 THEN 'JUNIO' WHEN 7 THEN 'JULIO' WHEN 8 THEN 'AGOSTO' WHEN 9 THEN 'SETIEMBRE' WHEN 10 THEN 'OCTUBRE' WHEN 11 THEN 'NOVIEMBRE' WHEN 12 THEN 'DICIEMBRE' END || ' ' || extract(YEAR FROM fechamonitoreo::date)::int AS campana, 'drene' AS tipo
FROM calidadaguadrenada2023.monitoreodrenajejunio WHERE (fechamonitoreo IS NOT NULL OR cooreste IS NOT NULL OR coornorte IS NOT NULL OR ce IS NOT NULL OR ph IS NOT NULL OR turbidez IS NOT NULL)
UNION ALL
SELECT btrim(upper(coalesce(nullif(ubicacion,''),'(SIN NOMBRE)'))) || '|' || coalesce(cooreste::text,'') || '|' || coalesce(coornorte::text,'') AS clv, geom, cooreste, coornorte, zona, cota, departamento, provincia, distrito, ubicacion, descripcion, aaa, ala, uh, fechamonitoreo::date AS fechamonitoreo, fechamonitoreo::date + horamonitoreo::time AS horamonitoreo, orden, ce, ph, std, t, turbidez, nitratos, nitritos, cromohexavalente, cobre, manganeso, sulfatos, hierro, zinc, cloruros, coliformestotales, coliformestermotolerantes, escherichiacoli, "dureza" AS "durezatotal", NULL::double precision AS "calcio", NULL::double precision AS "cloruro", NULL::double precision AS "potasio", NULL::double precision AS "sodio", NULL::double precision AS "amonio", NULL::double precision AS "magnesio", "observacion" AS "observaciones", CASE extract(MONTH FROM fechamonitoreo::date)::int WHEN 1 THEN 'ENERO' WHEN 2 THEN 'FEBRERO' WHEN 3 THEN 'MARZO' WHEN 4 THEN 'ABRIL' WHEN 5 THEN 'MAYO' WHEN 6 THEN 'JUNIO' WHEN 7 THEN 'JULIO' WHEN 8 THEN 'AGOSTO' WHEN 9 THEN 'SETIEMBRE' WHEN 10 THEN 'OCTUBRE' WHEN 11 THEN 'NOVIEMBRE' WHEN 12 THEN 'DICIEMBRE' END || ' ' || extract(YEAR FROM fechamonitoreo::date)::int AS campana, 'drene' AS tipo
FROM calidadaguadrenada2023.monitoreodrenajesetiembre WHERE (fechamonitoreo IS NOT NULL OR cooreste IS NOT NULL OR coornorte IS NOT NULL OR ce IS NOT NULL OR ph IS NOT NULL OR turbidez IS NOT NULL)
UNION ALL
SELECT btrim(upper(coalesce(nullif(ubicacion,''),'(SIN NOMBRE)'))) || '|' || coalesce(cooreste::text,'') || '|' || coalesce(coornorte::text,'') AS clv, geom, cooreste, coornorte, zona, cota, departamento, provincia, distrito, ubicacion, descripcion, aaa, ala, uh, fechamonitoreo::date AS fechamonitoreo, fechamonitoreo::date + horamonitoreo::time AS horamonitoreo, orden, ce, ph, std, t, turbidez, nitratos, nitritos, cromohexavalente, cobre, manganeso, sulfatos, hierro, zinc, cloruros, coliformestotales, coliformestermotolerantes, escherichiacoli, "durezatotal", "calcio", "cloruro", "potasio", "sodio", "amonio", "magnesio", "observacion" AS "observaciones", CASE extract(MONTH FROM fechamonitoreo::date)::int WHEN 1 THEN 'ENERO' WHEN 2 THEN 'FEBRERO' WHEN 3 THEN 'MARZO' WHEN 4 THEN 'ABRIL' WHEN 5 THEN 'MAYO' WHEN 6 THEN 'JUNIO' WHEN 7 THEN 'JULIO' WHEN 8 THEN 'AGOSTO' WHEN 9 THEN 'SETIEMBRE' WHEN 10 THEN 'OCTUBRE' WHEN 11 THEN 'NOVIEMBRE' WHEN 12 THEN 'DICIEMBRE' END || ' ' || extract(YEAR FROM fechamonitoreo::date)::int AS campana, 'drene' AS tipo
FROM calidadaguadrenada2024.monitoreodrenajeabril WHERE (fechamonitoreo IS NOT NULL OR cooreste IS NOT NULL OR coornorte IS NOT NULL OR ce IS NOT NULL OR ph IS NOT NULL OR turbidez IS NOT NULL)
UNION ALL
SELECT btrim(upper(coalesce(nullif(ubicacion,''),'(SIN NOMBRE)'))) || '|' || coalesce(cooreste::text,'') || '|' || coalesce(coornorte::text,'') AS clv, geom, cooreste, coornorte, zona, cota, departamento, provincia, distrito, ubicacion, descripcion, aaa, ala, uh, fechamonitoreo::date AS fechamonitoreo, fechamonitoreo::date + horamonitoreo::time AS horamonitoreo, orden, ce, ph, std, t, turbidez, nitratos, nitritos, cromohexavalente, cobre, manganeso, sulfatos, hierro, zinc, cloruros, coliformestotales, coliformestermotolerantes, escherichiacoli, "durezatotal", "calcio", "cloruro", "potasio", "sodio", "amonio", "magnesio", "observacion" AS "observaciones", CASE extract(MONTH FROM fechamonitoreo::date)::int WHEN 1 THEN 'ENERO' WHEN 2 THEN 'FEBRERO' WHEN 3 THEN 'MARZO' WHEN 4 THEN 'ABRIL' WHEN 5 THEN 'MAYO' WHEN 6 THEN 'JUNIO' WHEN 7 THEN 'JULIO' WHEN 8 THEN 'AGOSTO' WHEN 9 THEN 'SETIEMBRE' WHEN 10 THEN 'OCTUBRE' WHEN 11 THEN 'NOVIEMBRE' WHEN 12 THEN 'DICIEMBRE' END || ' ' || extract(YEAR FROM fechamonitoreo::date)::int AS campana, 'drene' AS tipo
FROM calidadaguadrenada2024.monitoreodrenajenoviembre WHERE (fechamonitoreo IS NOT NULL OR cooreste IS NOT NULL OR coornorte IS NOT NULL OR ce IS NOT NULL OR ph IS NOT NULL OR turbidez IS NOT NULL)
UNION ALL
SELECT btrim(upper(coalesce(nullif(ubicacion,''),'(SIN NOMBRE)'))) || '|' || coalesce(cooreste::text,'') || '|' || coalesce(coornorte::text,'') AS clv, geom, cooreste, coornorte, zona, cota, departamento, provincia, distrito, ubicacion, descripcion, aaa, ala, uh, fechamonitoreo::date AS fechamonitoreo, fechamonitoreo::date + horamonitoreo::time AS horamonitoreo, orden, ce, ph, std, t, turbidez, nitratos, nitritos, cromohexavalente, cobre, manganeso, sulfatos, hierro, zinc, cloruros, coliformestotales, coliformestermotolerantes, escherichiacoli, "durezatotal", "calcio", "cloruro", "potasio", "sodio", "amonio", "magnesio", "observaciones", CASE extract(MONTH FROM fechamonitoreo::date)::int WHEN 1 THEN 'ENERO' WHEN 2 THEN 'FEBRERO' WHEN 3 THEN 'MARZO' WHEN 4 THEN 'ABRIL' WHEN 5 THEN 'MAYO' WHEN 6 THEN 'JUNIO' WHEN 7 THEN 'JULIO' WHEN 8 THEN 'AGOSTO' WHEN 9 THEN 'SETIEMBRE' WHEN 10 THEN 'OCTUBRE' WHEN 11 THEN 'NOVIEMBRE' WHEN 12 THEN 'DICIEMBRE' END || ' ' || extract(YEAR FROM fechamonitoreo::date)::int AS campana, 'drene' AS tipo
FROM calidadaguadrenada2025.monitoreodrenajefebrero WHERE (fechamonitoreo IS NOT NULL OR cooreste IS NOT NULL OR coornorte IS NOT NULL OR ce IS NOT NULL OR ph IS NOT NULL OR turbidez IS NOT NULL)
UNION ALL
SELECT btrim(upper(coalesce(nullif(ubicacion,''),'(SIN NOMBRE)'))) || '|' || coalesce(cooreste::text,'') || '|' || coalesce(coornorte::text,'') AS clv, geom, cooreste, coornorte, zona, cota, departamento, provincia, distrito, ubicacion, descripcion, aaa, ala, uh, fechamonitoreo::date AS fechamonitoreo, fechamonitoreo::date + horamonitoreo::time AS horamonitoreo, orden, ce, ph, std, t, turbidez, nitratos, nitritos, cromohexavalente, cobre, manganeso, sulfatos, hierro, zinc, cloruros, coliformestotales, coliformestermotolerantes, escherichiacoli, "durezatotal", "calcio", "cloruro", "potasio", "sodio", "amonio", "magnesio", "observaciones", CASE extract(MONTH FROM fechamonitoreo::date)::int WHEN 1 THEN 'ENERO' WHEN 2 THEN 'FEBRERO' WHEN 3 THEN 'MARZO' WHEN 4 THEN 'ABRIL' WHEN 5 THEN 'MAYO' WHEN 6 THEN 'JUNIO' WHEN 7 THEN 'JULIO' WHEN 8 THEN 'AGOSTO' WHEN 9 THEN 'SETIEMBRE' WHEN 10 THEN 'OCTUBRE' WHEN 11 THEN 'NOVIEMBRE' WHEN 12 THEN 'DICIEMBRE' END || ' ' || extract(YEAR FROM fechamonitoreo::date)::int AS campana, 'drene' AS tipo
FROM calidadaguadrenada2025.monitoreodrenajejulio WHERE (fechamonitoreo IS NOT NULL OR cooreste IS NOT NULL OR coornorte IS NOT NULL OR ce IS NOT NULL OR ph IS NOT NULL OR turbidez IS NOT NULL)
UNION ALL
SELECT btrim(upper(coalesce(nullif(ubicacion,''),'(SIN NOMBRE)'))) || '|' || coalesce(cooreste::text,'') || '|' || coalesce(coornorte::text,'') AS clv, geom, cooreste, coornorte, zona, cota, departamento, provincia, distrito, ubicacion, descripcion, aaa, ala, uh, fechamonitoreo::date AS fechamonitoreo, fechamonitoreo::date + horamonitoreo::time AS horamonitoreo, orden, ce, ph, std, t, turbidez, nitratos, nitritos, cromohexavalente, cobre, manganeso, sulfatos, hierro, zinc, cloruros, coliformestotales, coliformestermotolerantes, escherichiacoli, "durezatotal", "calcio", "cloruro", "potasio", "sodio", "amonio", "magnesio", "observaciones", CASE extract(MONTH FROM fechamonitoreo::date)::int WHEN 1 THEN 'ENERO' WHEN 2 THEN 'FEBRERO' WHEN 3 THEN 'MARZO' WHEN 4 THEN 'ABRIL' WHEN 5 THEN 'MAYO' WHEN 6 THEN 'JUNIO' WHEN 7 THEN 'JULIO' WHEN 8 THEN 'AGOSTO' WHEN 9 THEN 'SETIEMBRE' WHEN 10 THEN 'OCTUBRE' WHEN 11 THEN 'NOVIEMBRE' WHEN 12 THEN 'DICIEMBRE' END || ' ' || extract(YEAR FROM fechamonitoreo::date)::int AS campana, 'drene' AS tipo
FROM calidadaguadrenada2025.monitoreodrenajeoctubre WHERE (fechamonitoreo IS NOT NULL OR cooreste IS NOT NULL OR coornorte IS NOT NULL OR ce IS NOT NULL OR ph IS NOT NULL OR turbidez IS NOT NULL)
UNION ALL
SELECT btrim(upper(coalesce(nullif(ubicacion,''),'(SIN NOMBRE)'))) || '|' || coalesce(cooreste::text,'') || '|' || coalesce(coornorte::text,'') AS clv, geom, cooreste, coornorte, zona, cota, departamento, provincia, distrito, ubicacion, descripcion, aaa, ala, uh, fechamonitoreo::date AS fechamonitoreo, fechamonitoreo::date + horamonitoreo::time AS horamonitoreo, orden, ce, ph, std, t, turbidez, nitratos, nitritos, cromohexavalente, cobre, manganeso, sulfatos, hierro, zinc, cloruros, coliformestotales, coliformestermotolerantes, escherichiacoli, "durezatotal", "calcio", "cloruro", "potasio", "sodio", "amonio", "magnesio", "observaciones", CASE extract(MONTH FROM fechamonitoreo::date)::int WHEN 1 THEN 'ENERO' WHEN 2 THEN 'FEBRERO' WHEN 3 THEN 'MARZO' WHEN 4 THEN 'ABRIL' WHEN 5 THEN 'MAYO' WHEN 6 THEN 'JUNIO' WHEN 7 THEN 'JULIO' WHEN 8 THEN 'AGOSTO' WHEN 9 THEN 'SETIEMBRE' WHEN 10 THEN 'OCTUBRE' WHEN 11 THEN 'NOVIEMBRE' WHEN 12 THEN 'DICIEMBRE' END || ' ' || extract(YEAR FROM fechamonitoreo::date)::int AS campana, 'drene' AS tipo
FROM calidadaguadrenada2026.monitoreodrenajemarzo WHERE (fechamonitoreo IS NOT NULL OR cooreste IS NOT NULL OR coornorte IS NOT NULL OR ce IS NOT NULL OR ph IS NOT NULL OR turbidez IS NOT NULL)
               UNION ALL
               SELECT btrim(upper(coalesce(nullif(ubicacion,''),'(SIN NOMBRE)'))) || '|' || coalesce(cooreste::text,'') || '|' || coalesce(coornorte::text,'') AS clv, geom, cooreste, coornorte, zona, cota, departamento, provincia, distrito, ubicacion, descripcion, aaa, ala, uh, fechamonitoreo::date AS fechamonitoreo, fechamonitoreo::date + horamonitoreo::time AS horamonitoreo, orden, ce, ph, std, t, turbidez, nitratos, nitritos, cromohexavalente, cobre, manganeso, sulfatos, hierro, zinc, cloruros, coliformestotales, coliformestermotolerantes, escherichiacoli, "durezatotal", NULL::double precision AS "calcio", NULL::double precision AS "cloruro", NULL::double precision AS "potasio", NULL::double precision AS "sodio", NULL::double precision AS "amonio", NULL::double precision AS "magnesio", "observacion" AS "observaciones", CASE extract(MONTH FROM fechamonitoreo::date)::int WHEN 1 THEN 'ENERO' WHEN 2 THEN 'FEBRERO' WHEN 3 THEN 'MARZO' WHEN 4 THEN 'ABRIL' WHEN 5 THEN 'MAYO' WHEN 6 THEN 'JUNIO' WHEN 7 THEN 'JULIO' WHEN 8 THEN 'AGOSTO' WHEN 9 THEN 'SETIEMBRE' WHEN 10 THEN 'OCTUBRE' WHEN 11 THEN 'NOVIEMBRE' WHEN 12 THEN 'DICIEMBRE' END || ' ' || extract(YEAR FROM fechamonitoreo::date)::int AS campana, 'calidad agua' AS tipo
FROM calidadaguasuperficial2022.monitoreosuperficialjunio WHERE (fechamonitoreo IS NOT NULL OR cooreste IS NOT NULL OR coornorte IS NOT NULL OR ce IS NOT NULL OR ph IS NOT NULL OR turbidez IS NOT NULL)
UNION ALL
SELECT btrim(upper(coalesce(nullif(ubicacion,''),'(SIN NOMBRE)'))) || '|' || coalesce(cooreste::text,'') || '|' || coalesce(coornorte::text,'') AS clv, geom, cooreste, coornorte, zona, cota, departamento, provincia, distrito, ubicacion, descripcion, aaa, ala, uh, fechamonitoreo::date AS fechamonitoreo, fechamonitoreo::date + horamonitoreo::time AS horamonitoreo, orden, ce, ph, std, t, turbidez, nitratos, nitritos, cromohexavalente, cobre, manganeso, sulfatos, hierro, zinc, cloruros, coliformestotales, coliformestermotolerantes, escherichiacoli, "durezatotal", NULL::double precision AS "calcio", NULL::double precision AS "cloruro", NULL::double precision AS "potasio", NULL::double precision AS "sodio", NULL::double precision AS "amonio", NULL::double precision AS "magnesio", "observacion" AS "observaciones", CASE extract(MONTH FROM fechamonitoreo::date)::int WHEN 1 THEN 'ENERO' WHEN 2 THEN 'FEBRERO' WHEN 3 THEN 'MARZO' WHEN 4 THEN 'ABRIL' WHEN 5 THEN 'MAYO' WHEN 6 THEN 'JUNIO' WHEN 7 THEN 'JULIO' WHEN 8 THEN 'AGOSTO' WHEN 9 THEN 'SETIEMBRE' WHEN 10 THEN 'OCTUBRE' WHEN 11 THEN 'NOVIEMBRE' WHEN 12 THEN 'DICIEMBRE' END || ' ' || extract(YEAR FROM fechamonitoreo::date)::int AS campana, 'calidad agua' AS tipo
FROM calidadaguasuperficial2022.monitoreosuperficialnoviembre WHERE (fechamonitoreo IS NOT NULL OR cooreste IS NOT NULL OR coornorte IS NOT NULL OR ce IS NOT NULL OR ph IS NOT NULL OR turbidez IS NOT NULL)
UNION ALL
SELECT btrim(upper(coalesce(nullif(ubicacion,''),'(SIN NOMBRE)'))) || '|' || coalesce(cooreste::text,'') || '|' || coalesce(coornorte::text,'') AS clv, geom, cooreste, coornorte, zona, cota, departamento, provincia, distrito, ubicacion, descripcion, aaa, ala, uh, fechamonitoreo::date AS fechamonitoreo, fechamonitoreo::date + horamonitoreo::time AS horamonitoreo, orden, ce, ph, std, t, turbidez, nitratos, nitritos, cromohexavalente, cobre, manganeso, sulfatos, hierro, zinc, cloruros, coliformestotales, coliformestermotolerantes, escherichiacoli, "durezatotal", NULL::double precision AS "calcio", NULL::double precision AS "cloruro", NULL::double precision AS "potasio", NULL::double precision AS "sodio", NULL::double precision AS "amonio", NULL::double precision AS "magnesio", "observacion" AS "observaciones", CASE extract(MONTH FROM fechamonitoreo::date)::int WHEN 1 THEN 'ENERO' WHEN 2 THEN 'FEBRERO' WHEN 3 THEN 'MARZO' WHEN 4 THEN 'ABRIL' WHEN 5 THEN 'MAYO' WHEN 6 THEN 'JUNIO' WHEN 7 THEN 'JULIO' WHEN 8 THEN 'AGOSTO' WHEN 9 THEN 'SETIEMBRE' WHEN 10 THEN 'OCTUBRE' WHEN 11 THEN 'NOVIEMBRE' WHEN 12 THEN 'DICIEMBRE' END || ' ' || extract(YEAR FROM fechamonitoreo::date)::int AS campana, 'calidad agua' AS tipo
FROM calidadaguasuperficial2022.monitoreosuperficialsetiembre WHERE (fechamonitoreo IS NOT NULL OR cooreste IS NOT NULL OR coornorte IS NOT NULL OR ce IS NOT NULL OR ph IS NOT NULL OR turbidez IS NOT NULL)
UNION ALL
SELECT btrim(upper(coalesce(nullif(ubicacion,''),'(SIN NOMBRE)'))) || '|' || coalesce(cooreste::text,'') || '|' || coalesce(coornorte::text,'') AS clv, geom, cooreste, coornorte, zona, cota, departamento, provincia, distrito, ubicacion, descripcion, aaa, ala, uh, fechamonitoreo::date AS fechamonitoreo, fechamonitoreo::date + horamonitoreo::time AS horamonitoreo, orden, ce, ph, std, t, turbidez, nitratos, nitritos, cromohexavalente, cobre, manganeso, sulfatos, hierro, zinc, cloruros, coliformestotales, coliformestermotolerantes, escherichiacoli, "durezatotal", NULL::double precision AS "calcio", NULL::double precision AS "cloruro", NULL::double precision AS "potasio", NULL::double precision AS "sodio", NULL::double precision AS "amonio", NULL::double precision AS "magnesio", "observacion" AS "observaciones", CASE extract(MONTH FROM fechamonitoreo::date)::int WHEN 1 THEN 'ENERO' WHEN 2 THEN 'FEBRERO' WHEN 3 THEN 'MARZO' WHEN 4 THEN 'ABRIL' WHEN 5 THEN 'MAYO' WHEN 6 THEN 'JUNIO' WHEN 7 THEN 'JULIO' WHEN 8 THEN 'AGOSTO' WHEN 9 THEN 'SETIEMBRE' WHEN 10 THEN 'OCTUBRE' WHEN 11 THEN 'NOVIEMBRE' WHEN 12 THEN 'DICIEMBRE' END || ' ' || extract(YEAR FROM fechamonitoreo::date)::int AS campana, 'calidad agua' AS tipo
FROM calidadaguasuperficial2023.monitoreosuperficialagosto WHERE (fechamonitoreo IS NOT NULL OR cooreste IS NOT NULL OR coornorte IS NOT NULL OR ce IS NOT NULL OR ph IS NOT NULL OR turbidez IS NOT NULL)
UNION ALL
SELECT btrim(upper(coalesce(nullif(ubicacion,''),'(SIN NOMBRE)'))) || '|' || coalesce(cooreste::text,'') || '|' || coalesce(coornorte::text,'') AS clv, geom, cooreste, coornorte, zona, cota, departamento, provincia, distrito, ubicacion, descripcion, aaa, ala, uh, fechamonitoreo::date AS fechamonitoreo, fechamonitoreo::date + horamonitoreo::time AS horamonitoreo, orden, ce, ph, std, t, turbidez, nitratos, nitritos, cromohexavalente, cobre, manganeso, sulfatos, hierro, zinc, cloruros, coliformestotales, coliformestermotolerantes, escherichiacoli, "durezatotal", NULL::double precision AS "calcio", NULL::double precision AS "cloruro", NULL::double precision AS "potasio", NULL::double precision AS "sodio", NULL::double precision AS "amonio", NULL::double precision AS "magnesio", "observacion" AS "observaciones", CASE extract(MONTH FROM fechamonitoreo::date)::int WHEN 1 THEN 'ENERO' WHEN 2 THEN 'FEBRERO' WHEN 3 THEN 'MARZO' WHEN 4 THEN 'ABRIL' WHEN 5 THEN 'MAYO' WHEN 6 THEN 'JUNIO' WHEN 7 THEN 'JULIO' WHEN 8 THEN 'AGOSTO' WHEN 9 THEN 'SETIEMBRE' WHEN 10 THEN 'OCTUBRE' WHEN 11 THEN 'NOVIEMBRE' WHEN 12 THEN 'DICIEMBRE' END || ' ' || extract(YEAR FROM fechamonitoreo::date)::int AS campana, 'calidad agua' AS tipo
FROM calidadaguasuperficial2023.monitoreosuperficialdiciembre WHERE (fechamonitoreo IS NOT NULL OR cooreste IS NOT NULL OR coornorte IS NOT NULL OR ce IS NOT NULL OR ph IS NOT NULL OR turbidez IS NOT NULL)
UNION ALL
SELECT btrim(upper(coalesce(nullif(ubicacion,''),'(SIN NOMBRE)'))) || '|' || coalesce(cooreste::text,'') || '|' || coalesce(coornorte::text,'') AS clv, geom, cooreste, coornorte, zona, cota, departamento, provincia, distrito, ubicacion, descripcion, aaa, ala, uh, fechamonitoreo::date AS fechamonitoreo, fechamonitoreo::date + horamonitoreo::time AS horamonitoreo, orden, ce, ph, std, t, turbidez, nitratos, nitritos, cromohexavalente, cobre, manganeso, sulfatos, hierro, zinc, cloruros, coliformestotales, coliformestermotolerantes, escherichiacoli, "durezatotal", NULL::double precision AS "calcio", NULL::double precision AS "cloruro", NULL::double precision AS "potasio", NULL::double precision AS "sodio", NULL::double precision AS "amonio", NULL::double precision AS "magnesio", "observacion" AS "observaciones", CASE extract(MONTH FROM fechamonitoreo::date)::int WHEN 1 THEN 'ENERO' WHEN 2 THEN 'FEBRERO' WHEN 3 THEN 'MARZO' WHEN 4 THEN 'ABRIL' WHEN 5 THEN 'MAYO' WHEN 6 THEN 'JUNIO' WHEN 7 THEN 'JULIO' WHEN 8 THEN 'AGOSTO' WHEN 9 THEN 'SETIEMBRE' WHEN 10 THEN 'OCTUBRE' WHEN 11 THEN 'NOVIEMBRE' WHEN 12 THEN 'DICIEMBRE' END || ' ' || extract(YEAR FROM fechamonitoreo::date)::int AS campana, 'calidad agua' AS tipo
FROM calidadaguasuperficial2023.monitoreosuperficialmayo WHERE (fechamonitoreo IS NOT NULL OR cooreste IS NOT NULL OR coornorte IS NOT NULL OR ce IS NOT NULL OR ph IS NOT NULL OR turbidez IS NOT NULL)
UNION ALL
SELECT btrim(upper(coalesce(nullif(ubicacion,''),'(SIN NOMBRE)'))) || '|' || coalesce(cooreste::text,'') || '|' || coalesce(coornorte::text,'') AS clv, geom, cooreste, coornorte, zona, cota, departamento, provincia, distrito, ubicacion, descripcion, aaa, ala, uh, fechamonitoreo::date AS fechamonitoreo, fechamonitoreo::date + horamonitoreo::time AS horamonitoreo, orden, ce, ph, std, t, turbidez, nitratos, nitritos, cromohexavalente, cobre, manganeso, sulfatos, hierro, zinc, cloruros, coliformestotales, coliformestermotolerantes, escherichiacoli, "durezatotal", NULL::double precision AS "calcio", NULL::double precision AS "cloruro", NULL::double precision AS "potasio", NULL::double precision AS "sodio", NULL::double precision AS "amonio", NULL::double precision AS "magnesio", "observacion" AS "observaciones", CASE extract(MONTH FROM fechamonitoreo::date)::int WHEN 1 THEN 'ENERO' WHEN 2 THEN 'FEBRERO' WHEN 3 THEN 'MARZO' WHEN 4 THEN 'ABRIL' WHEN 5 THEN 'MAYO' WHEN 6 THEN 'JUNIO' WHEN 7 THEN 'JULIO' WHEN 8 THEN 'AGOSTO' WHEN 9 THEN 'SETIEMBRE' WHEN 10 THEN 'OCTUBRE' WHEN 11 THEN 'NOVIEMBRE' WHEN 12 THEN 'DICIEMBRE' END || ' ' || extract(YEAR FROM fechamonitoreo::date)::int AS campana, 'calidad agua' AS tipo
FROM calidadaguasuperficial2023.monitoreosuperficialoctubre WHERE (fechamonitoreo IS NOT NULL OR cooreste IS NOT NULL OR coornorte IS NOT NULL OR ce IS NOT NULL OR ph IS NOT NULL OR turbidez IS NOT NULL)
UNION ALL
SELECT btrim(upper(coalesce(nullif(ubicacion,''),'(SIN NOMBRE)'))) || '|' || coalesce(cooreste::text,'') || '|' || coalesce(coornorte::text,'') AS clv, geom, cooreste, coornorte, zona, cota, departamento, provincia, distrito, ubicacion, descripcion, aaa, ala, uh, fechamonitoreo::date AS fechamonitoreo, fechamonitoreo::date + horamonitoreo::time AS horamonitoreo, orden, ce, ph, std, t, turbidez, nitratos, nitritos, cromohexavalente, cobre, manganeso, sulfatos, hierro, zinc, cloruros, coliformestotales, coliformestermotolerantes, escherichiacoli, "durezatotal", "calcio", "cloruro", "potasio", "sodio", "amonio", "magnesio", "observacion" AS "observaciones", CASE extract(MONTH FROM fechamonitoreo::date)::int WHEN 1 THEN 'ENERO' WHEN 2 THEN 'FEBRERO' WHEN 3 THEN 'MARZO' WHEN 4 THEN 'ABRIL' WHEN 5 THEN 'MAYO' WHEN 6 THEN 'JUNIO' WHEN 7 THEN 'JULIO' WHEN 8 THEN 'AGOSTO' WHEN 9 THEN 'SETIEMBRE' WHEN 10 THEN 'OCTUBRE' WHEN 11 THEN 'NOVIEMBRE' WHEN 12 THEN 'DICIEMBRE' END || ' ' || extract(YEAR FROM fechamonitoreo::date)::int AS campana, 'calidad agua' AS tipo
FROM calidadaguasuperficial2024.monitoreosuperficialjunio WHERE (fechamonitoreo IS NOT NULL OR cooreste IS NOT NULL OR coornorte IS NOT NULL OR ce IS NOT NULL OR ph IS NOT NULL OR turbidez IS NOT NULL)
UNION ALL
SELECT btrim(upper(coalesce(nullif(ubicacion,''),'(SIN NOMBRE)'))) || '|' || coalesce(cooreste::text,'') || '|' || coalesce(coornorte::text,'') AS clv, geom, cooreste, coornorte, zona, cota, departamento, provincia, distrito, ubicacion, descripcion, aaa, ala, uh, fechamonitoreo::date AS fechamonitoreo, fechamonitoreo::date + horamonitoreo::time AS horamonitoreo, orden, ce, ph, std, t, turbidez, nitratos, nitritos, cromohexavalente, cobre, manganeso, sulfatos, hierro, zinc, cloruros, coliformestotales, coliformestermotolerantes, escherichiacoli, "durezatotal", "calcio", "cloruro", "potasio", "sodio", "amonio", "magnesio", "observacion" AS "observaciones", CASE extract(MONTH FROM fechamonitoreo::date)::int WHEN 1 THEN 'ENERO' WHEN 2 THEN 'FEBRERO' WHEN 3 THEN 'MARZO' WHEN 4 THEN 'ABRIL' WHEN 5 THEN 'MAYO' WHEN 6 THEN 'JUNIO' WHEN 7 THEN 'JULIO' WHEN 8 THEN 'AGOSTO' WHEN 9 THEN 'SETIEMBRE' WHEN 10 THEN 'OCTUBRE' WHEN 11 THEN 'NOVIEMBRE' WHEN 12 THEN 'DICIEMBRE' END || ' ' || extract(YEAR FROM fechamonitoreo::date)::int AS campana, 'calidad agua' AS tipo
FROM calidadaguasuperficial2024.monitoreosuperficialnoviembre WHERE (fechamonitoreo IS NOT NULL OR cooreste IS NOT NULL OR coornorte IS NOT NULL OR ce IS NOT NULL OR ph IS NOT NULL OR turbidez IS NOT NULL)
UNION ALL
SELECT btrim(upper(coalesce(nullif(ubicacion,''),'(SIN NOMBRE)'))) || '|' || coalesce(cooreste::text,'') || '|' || coalesce(coornorte::text,'') AS clv, geom, cooreste, coornorte, zona, cota, departamento, provincia, distrito, ubicacion, descripcion, aaa, ala, uh, fechamonitoreo::date AS fechamonitoreo, fechamonitoreo::date + horamonitoreo::time AS horamonitoreo, orden, ce, ph, std, t, turbidez, nitratos, nitritos, cromohexavalente, cobre, manganeso, sulfatos, hierro, zinc, cloruros, coliformestotales, coliformestermotolerantes, escherichiacoli, "durezatotal", "calcio", "cloruro", "potasio", "sodio", "amonio", "magnesio", "observaciones", CASE extract(MONTH FROM fechamonitoreo::date)::int WHEN 1 THEN 'ENERO' WHEN 2 THEN 'FEBRERO' WHEN 3 THEN 'MARZO' WHEN 4 THEN 'ABRIL' WHEN 5 THEN 'MAYO' WHEN 6 THEN 'JUNIO' WHEN 7 THEN 'JULIO' WHEN 8 THEN 'AGOSTO' WHEN 9 THEN 'SETIEMBRE' WHEN 10 THEN 'OCTUBRE' WHEN 11 THEN 'NOVIEMBRE' WHEN 12 THEN 'DICIEMBRE' END || ' ' || extract(YEAR FROM fechamonitoreo::date)::int AS campana, 'calidad agua' AS tipo
FROM calidadaguasuperficial2025.monitoreosuperficialdiciembre WHERE (fechamonitoreo IS NOT NULL OR cooreste IS NOT NULL OR coornorte IS NOT NULL OR ce IS NOT NULL OR ph IS NOT NULL OR turbidez IS NOT NULL)
UNION ALL
SELECT btrim(upper(coalesce(nullif(ubicacion,''),'(SIN NOMBRE)'))) || '|' || coalesce(cooreste::text,'') || '|' || coalesce(coornorte::text,'') AS clv, geom, cooreste, coornorte, zona, cota, departamento, provincia, distrito, ubicacion, descripcion, aaa, ala, uh, fechamonitoreo::date AS fechamonitoreo, fechamonitoreo::date + horamonitoreo::time AS horamonitoreo, orden, ce, ph, std, t, turbidez, nitratos, nitritos, cromohexavalente, cobre, manganeso, sulfatos, hierro, zinc, cloruros, coliformestotales, coliformestermotolerantes, escherichiacoli, "durezatotal", "calcio", "cloruro", "potasio", "sodio", "amonio", "magnesio", "observaciones", CASE extract(MONTH FROM fechamonitoreo::date)::int WHEN 1 THEN 'ENERO' WHEN 2 THEN 'FEBRERO' WHEN 3 THEN 'MARZO' WHEN 4 THEN 'ABRIL' WHEN 5 THEN 'MAYO' WHEN 6 THEN 'JUNIO' WHEN 7 THEN 'JULIO' WHEN 8 THEN 'AGOSTO' WHEN 9 THEN 'SETIEMBRE' WHEN 10 THEN 'OCTUBRE' WHEN 11 THEN 'NOVIEMBRE' WHEN 12 THEN 'DICIEMBRE' END || ' ' || extract(YEAR FROM fechamonitoreo::date)::int AS campana, 'calidad agua' AS tipo
FROM calidadaguasuperficial2025.monitoreosuperficialjulio WHERE (fechamonitoreo IS NOT NULL OR cooreste IS NOT NULL OR coornorte IS NOT NULL OR ce IS NOT NULL OR ph IS NOT NULL OR turbidez IS NOT NULL)
UNION ALL
SELECT btrim(upper(coalesce(nullif(ubicacion,''),'(SIN NOMBRE)'))) || '|' || coalesce(cooreste::text,'') || '|' || coalesce(coornorte::text,'') AS clv, geom, cooreste, coornorte, zona, cota, departamento, provincia, distrito, ubicacion, descripcion, aaa, ala, uh, fechamonitoreo::date AS fechamonitoreo, fechamonitoreo::date + horamonitoreo::time AS horamonitoreo, orden, ce, ph, std, t, turbidez, nitratos, nitritos, cromohexavalente, cobre, manganeso, sulfatos, hierro, zinc, cloruros, coliformestotales, coliformestermotolerantes, escherichiacoli, "durezatotal", "calcio", "cloruro", "potasio", "sodio", "amonio", "magnesio", "observaciones", CASE extract(MONTH FROM fechamonitoreo::date)::int WHEN 1 THEN 'ENERO' WHEN 2 THEN 'FEBRERO' WHEN 3 THEN 'MARZO' WHEN 4 THEN 'ABRIL' WHEN 5 THEN 'MAYO' WHEN 6 THEN 'JUNIO' WHEN 7 THEN 'JULIO' WHEN 8 THEN 'AGOSTO' WHEN 9 THEN 'SETIEMBRE' WHEN 10 THEN 'OCTUBRE' WHEN 11 THEN 'NOVIEMBRE' WHEN 12 THEN 'DICIEMBRE' END || ' ' || extract(YEAR FROM fechamonitoreo::date)::int AS campana, 'calidad agua' AS tipo
FROM calidadaguasuperficial2025.monitoreosuperficialmarzo WHERE (fechamonitoreo IS NOT NULL OR cooreste IS NOT NULL OR coornorte IS NOT NULL OR ce IS NOT NULL OR ph IS NOT NULL OR turbidez IS NOT NULL)
UNION ALL
SELECT btrim(upper(coalesce(nullif(ubicacion,''),'(SIN NOMBRE)'))) || '|' || coalesce(cooreste::text,'') || '|' || coalesce(coornorte::text,'') AS clv, geom, cooreste, coornorte, zona, cota, departamento, provincia, distrito, ubicacion, descripcion, aaa, ala, uh, fechamonitoreo::date AS fechamonitoreo, fechamonitoreo::date + horamonitoreo::time AS horamonitoreo, orden, ce, ph, std, t, turbidez, nitratos, nitritos, cromohexavalente, cobre, manganeso, sulfatos, hierro, zinc, cloruros, coliformestotales, coliformestermotolerantes, escherichiacoli, "durezatotal", "calcio", "cloruro", "potasio", "sodio", "amonio", "magnesio", "observaciones", CASE extract(MONTH FROM fechamonitoreo::date)::int WHEN 1 THEN 'ENERO' WHEN 2 THEN 'FEBRERO' WHEN 3 THEN 'MARZO' WHEN 4 THEN 'ABRIL' WHEN 5 THEN 'MAYO' WHEN 6 THEN 'JUNIO' WHEN 7 THEN 'JULIO' WHEN 8 THEN 'AGOSTO' WHEN 9 THEN 'SETIEMBRE' WHEN 10 THEN 'OCTUBRE' WHEN 11 THEN 'NOVIEMBRE' WHEN 12 THEN 'DICIEMBRE' END || ' ' || extract(YEAR FROM fechamonitoreo::date)::int AS campana, 'calidad agua' AS tipo
FROM calidadaguasuperficial2025.monitoreosuperficialnoviembre WHERE (fechamonitoreo IS NOT NULL OR cooreste IS NOT NULL OR coornorte IS NOT NULL OR ce IS NOT NULL OR ph IS NOT NULL OR turbidez IS NOT NULL)
UNION ALL
SELECT btrim(upper(coalesce(nullif(ubicacion,''),'(SIN NOMBRE)'))) || '|' || coalesce(cooreste::text,'') || '|' || coalesce(coornorte::text,'') AS clv, geom, cooreste, coornorte, zona, cota, departamento, provincia, distrito, ubicacion, descripcion, aaa, ala, uh, fechamonitoreo::date AS fechamonitoreo, fechamonitoreo::date + horamonitoreo::time AS horamonitoreo, orden, ce, ph, std, t, turbidez, nitratos, nitritos, cromohexavalente, cobre, manganeso, sulfatos, hierro, zinc, cloruros, coliformestotales, coliformestermotolerantes, escherichiacoli, "durezatotal", "calcio", "cloruro", "potasio", "sodio", "amonio", "magnesio", "observaciones", CASE extract(MONTH FROM fechamonitoreo::date)::int WHEN 1 THEN 'ENERO' WHEN 2 THEN 'FEBRERO' WHEN 3 THEN 'MARZO' WHEN 4 THEN 'ABRIL' WHEN 5 THEN 'MAYO' WHEN 6 THEN 'JUNIO' WHEN 7 THEN 'JULIO' WHEN 8 THEN 'AGOSTO' WHEN 9 THEN 'SETIEMBRE' WHEN 10 THEN 'OCTUBRE' WHEN 11 THEN 'NOVIEMBRE' WHEN 12 THEN 'DICIEMBRE' END || ' ' || extract(YEAR FROM fechamonitoreo::date)::int AS campana, 'calidad agua' AS tipo
FROM calidadaguasuperficial2026.monitoreosuperficialagosto WHERE (fechamonitoreo IS NOT NULL OR cooreste IS NOT NULL OR coornorte IS NOT NULL OR ce IS NOT NULL OR ph IS NOT NULL OR turbidez IS NOT NULL)
UNION ALL
SELECT btrim(upper(coalesce(nullif(ubicacion,''),'(SIN NOMBRE)'))) || '|' || coalesce(cooreste::text,'') || '|' || coalesce(coornorte::text,'') AS clv, geom, cooreste, coornorte, zona, cota, departamento, provincia, distrito, ubicacion, descripcion, aaa, ala, uh, fechamonitoreo::date AS fechamonitoreo, fechamonitoreo::date + horamonitoreo::time AS horamonitoreo, orden, ce, ph, std, t, turbidez, nitratos, nitritos, cromohexavalente, cobre, manganeso, sulfatos, hierro, zinc, cloruros, coliformestotales, coliformestermotolerantes, escherichiacoli, "durezatotal", "calcio", "cloruro", "potasio", "sodio", "amonio", "magnesio", "observaciones", CASE extract(MONTH FROM fechamonitoreo::date)::int WHEN 1 THEN 'ENERO' WHEN 2 THEN 'FEBRERO' WHEN 3 THEN 'MARZO' WHEN 4 THEN 'ABRIL' WHEN 5 THEN 'MAYO' WHEN 6 THEN 'JUNIO' WHEN 7 THEN 'JULIO' WHEN 8 THEN 'AGOSTO' WHEN 9 THEN 'SETIEMBRE' WHEN 10 THEN 'OCTUBRE' WHEN 11 THEN 'NOVIEMBRE' WHEN 12 THEN 'DICIEMBRE' END || ' ' || extract(YEAR FROM fechamonitoreo::date)::int AS campana, 'calidad agua' AS tipo
FROM calidadaguasuperficial2026.monitoreosuperficialmarzo WHERE (fechamonitoreo IS NOT NULL OR cooreste IS NOT NULL OR coornorte IS NOT NULL OR ce IS NOT NULL OR ph IS NOT NULL OR turbidez IS NOT NULL) ) u
        LEFT JOIN hidrologia.drenes_catastro d
          ON btrim(upper(coalesce(nullif(d.ubicacion,''),'(SIN NOMBRE)'))) || '|'
             || coalesce(d.cooreste::text,'') || '|' || coalesce(d.coornorte::text,'') = u.clv
        LEFT JOIN hidrologia.calidad_catastro c
          ON btrim(upper(coalesce(nullif(c.ubicacion,''),'(SIN NOMBRE)'))) || '|'
             || coalesce(c.cooreste::text,'') || '|' || coalesce(c.coornorte::text,'') = u.clv
    LOOP
        IF r.id_catalogo IS NULL THEN
            RAISE NOTICE 'SIN CATALOGO: %', r.clv;
            CONTINUE;
        END IF;

        INSERT INTO hidrologia.pozos_monitoreo
            (id_pozo, id_dren, id_calidad, tipo, monitoreo, fechamonitoreo, horamonitoreo,
             ce, ph, std, t, observaciones)
        VALUES
            (NULL,
             CASE WHEN r.tipo='drene' THEN r.id_catalogo END,
             CASE WHEN r.tipo='calidad agua' THEN r.id_catalogo END,
             r.tipo, r.campana, r.fechamonitoreo, r.horamonitoreo,
             r.ce, r.ph, r.std, r.t, left(nullif(r.observaciones,''),100))
        RETURNING id_medicion INTO newmed;

        INSERT INTO hidrologia.calidad_agua_laboratorio
            (id_pozo, id_medicion, id_dren, id_calidad, orden, tipo, fecha_toma_muestra,
             turbidez, durezatotal, nitratos, nitritos, sulfatos, cloruros, cloruro, amonio,
             cromohexavalente, cobre, manganeso, hierro, zinc, calcio, potasio, sodio, magnesio,
             coliformestotales, coliformestermotolerantes, escherichiacoli, observaciones)
        VALUES
            (NULL, newmed,
             CASE WHEN r.tipo='drene' THEN r.id_catalogo END,
             CASE WHEN r.tipo='calidad agua' THEN r.id_catalogo END,
             r.orden::int, r.tipo, r.fechamonitoreo,
             r.turbidez::text, r.durezatotal::text, r.nitratos::text, r.nitritos::text,
             r.sulfatos::text, r.cloruros::text, r.cloruro::text, r.amonio::text,
             r.cromohexavalente::text, r.cobre::text, r.manganeso::text, r.hierro::text,
             r.zinc::text, r.calcio::text, r.potasio::text, r.sodio::text, r.magnesio::text,
             r.coliformestotales::text, r.coliformestermotolerantes::text,
             r.escherichiacoli::text, nullif(r.observaciones,''));
        n_th := n_th + 1;
    END LOOP;

    RAISE NOTICE 'MEDICIONES MIGRADAS: %', n_th;
END $$;

COMMIT;
