SELECT btrim(upper(coalesce(nullif(ubicacion,''),'(SIN NOMBRE)'))) || '|' || coalesce(cooreste::text,'') || '|' || coalesce(coornorte::text,'') AS clv, geom, cooreste, coornorte, zona, cota, departamento, provincia, distrito, ubicacion, descripcion, aaa, ala, uh, fechamonitoreo::date AS fechamonitoreo, fechamonitoreo::date + horamonitoreo::time AS horamonitoreo, orden, ce, ph, std, t, turbidez, nitratos, nitritos, cromohexavalente, cobre, manganeso, sulfatos, hierro, zinc, cloruros, coliformestotales, coliformestermotolerantes, escherichiacoli, "durezatotal", NULL::double precision AS "calcio", NULL::double precision AS "cloruro", NULL::double precision AS "potasio", NULL::double precision AS "sodio", NULL::double precision AS "amonio", NULL::double precision AS "magnesio", "observacion" AS "observaciones", CASE extract(MONTH FROM fechamonitoreo::date)::int WHEN 1 THEN 'ENERO' WHEN 2 THEN 'FEBRERO' WHEN 3 THEN 'MARZO' WHEN 4 THEN 'ABRIL' WHEN 5 THEN 'MAYO' WHEN 6 THEN 'JUNIO' WHEN 7 THEN 'JULIO' WHEN 8 THEN 'AGOSTO' WHEN 9 THEN 'SETIEMBRE' WHEN 10 THEN 'OCTUBRE' WHEN 11 THEN 'NOVIEMBRE' WHEN 12 THEN 'DICIEMBRE' END || ' ' || extract(YEAR FROM fechamonitoreo::date)::int AS campana, 'calidad agua' AS tipo
FROM calidadaguasuperficial2022.monitoreosuperficialjunio WHERE (fechamonitoreo IS NOT NULL OR cooreste IS NOT NULL OR coornorte IS NOT NULL OR ce IS NOT NULL OR ph IS NOT NULL OR turbidez IS NOT NULL)
UNION ALL
SELECT btrim(upper(coalesce(nullif(ubicacion,''),'(SIN NOMBRE)'))) || '|' || coalesce(cooreste::text,'') || '|' || coalesce(coornorte::text,'') AS clv, geom, cooreste, coornorte, zona, cota, departamento, provincia, distrito, ubicacion, descripcion, aaa, ala, uh, fechamonitoreo::date AS fechamonitoreo, fechamonitoreo::date + horamonitoreo::time AS horamonitoreo, orden, ce, ph, std, t, turbidez, nitratos, nitritos, cromohexavalente, cobre, manganeso, sulfatos, hierro, zinc, cloruros, coliformestotales, coliformestermotolerantes, escherichiacoli, "durezatotal", NULL::double precision AS "calcio", NULL::double precision AS "cloruro", NULL::double precision AS "potasio", NULL::double precision AS "sodio", NULL::double precision AS "amonio", NULL::double precision AS "magnesio", "observacion" AS "observaciones", CASE extract(MONTH FROM fechamonitoreo::date)::int WHEN 1 THEN 'ENERO' WHEN 2 THEN 'FEBRERO' WHEN 3 THEN 'MARZO' WHEN 4 THEN 'ABRIL' WHEN 5 THEN 'MAYO' WHEN 6 THEN 'JUNIO' WHEN 7 THEN 'JULIO' WHEN 8 THEN 'AGOSTO' WHEN 9 THEN 'SETIEMBRE' WHEN 10 THEN 'OCTUBRE' WHEN 11 THEN 'NOVIEMBRE' WHEN 12 THEN 'DICIEMBRE' END || ' ' || extract(YEAR FROM fechamonitoreo::date)::int AS campana, 'calidad agua' AS tipo
FROM calidadaguasuperficial2022.monitoreosuperficialnoviembre WHERE (fechamonitoreo IS NOT NULL OR cooreste IS NOT NULL OR coornorte IS NOT NULL OR ce IS NOT NULL OR ph IS NOT NULL OR turbidez IS NOT NULL)
UNION ALL
SELECT btrim(upper(coalesce(nullif(ubicacion,''),'(SIN NOMBRE)'))) || '|' || coalesce(cooreste::text,'') || '|' || coalesce(coornorte::text,'') AS clv, geom, cooreste, coornorte, zona, cota, departamento, provincia, distrito, ubicacion, descripcion, aaa, ala, uh, fechamonitoreo::date AS fechamonitoreo, fechamonitoreo::date + horamonitoreo::time AS horamonitoreo, orden, ce, ph, std, t, turbidez, nitratos, nitritos, cromohexavalente, cobre, manganeso, sulfatos, hierro, zinc, cloruros, coliformestotales, coliformestermotolerantes, escherichiacoli, "durezatotal", NULL::double precision AS "calcio", NULL::double precision AS "cloruro", NULL::double precision AS "potasio", NULL::double precision AS "sodio", NULL::double precision AS "amonio", NULL::double precision AS "magnesio", "observacion" AS "observaciones", CASE extract(MONTH FROM fechamonitoreo::date)::int WHEN 1 THEN 'ENERO' WHEN 2 THEN 'FEBRERO' WHEN 3 THEN 'MARZO' WHEN 4 THEN 'ABRIL' WHEN 5 THEN 'MAYO' WHEN 6 THEN 'JUNIO' WHEN 7 THEN 'JULIO' WHEN 8 THEN 'AGOSTO' WHEN 9 THEN 'SETIEMBRE' WHEN 10 THEN 'OCTUBRE' WHEN 11 THEN 'NOVIEMBRE' WHEN 12 THEN 'DICIEMBRE' END || ' ' || extract(YEAR FROM fechamonitoreo::date)::int AS campana, 'calidad agua' AS tipo
FROM calidadaguasuperficial2022.monitoreosuperficialsetiembre WHERE (fechamonitoreo IS NOT NULL OR cooreste IS NOT NULL OR coornorte IS NOT NULL OR ce IS NOT NULL OR ph IS NOT NULL OR turbidez IS NOT NULL)
UNION ALL
SELECT btrim(upper(coalesce(nullif(ubicacion,''),'(SIN NOMBRE)'))) || '|' || coalesce(cooreste::text,'') || '|' || coalesce(coornorte::text,'') AS clv, geom, cooreste, coornorte, zona, cota, departamento, provincia, distrito, ubicacion, descripcion, aaa, ala, uh, fechamonitoreo::date AS fechamonitoreo, fechamonitoreo::date + horamonitoreo::time AS horamonitoreo, orden, ce, ph, std, t, turbidez, nitratos, nitritos, cromohexavalente, cobre, manganeso, sulfatos, hierro, zinc, cloruros, coliformestotales, coliformestermotolerantes, escherichiacoli, "durezatotal", NULL::double precision AS "calcio", NULL::double precision AS "cloruro", NULL::double precision AS "potasio", NULL::double precision AS "sodio", NULL::double precision AS "amonio", NULL::double precision AS "magnesio", "observacion" AS "observaciones", CASE extract(MONTH FROM fechamonitoreo::date)::int WHEN 1 THEN 'ENERO' WHEN 2 THEN 'FEBRERO' WHEN 3 THEN 'MARZO' WHEN 4 THEN 'ABRIL' WHEN 5 THEN 'MAYO' WHEN 6 THEN 'JUNIO' WHEN 7 THEN 'JULIO' WHEN 8 THEN 'AGOSTO' WHEN 9 THEN 'SETIEMBRE' WHEN 10 THEN 'OCTUBRE' WHEN 11 THEN 'NOVIEMBRE' WHEN 12 THEN 'DICIEMBRE' END || ' ' || extract(YEAR FROM fechamonitoreo::date)::int AS campana, 'calidad agua' AS tipo
FROM calidadaguasuperficial2023.monitoreosuperficialagosto WHERE (fechamonitoreo IS NOT NULL OR cooreste IS NOT NULL OR coornorte IS NOT NULL OR ce IS NOT NULL OR ph IS NOT NULL OR turbidez IS NOT NULL)
UNION ALL
SELECT btrim(upper(coalesce(nullif(ubicacion,''),'(SIN NOMBRE)'))) || '|' || coalesce(cooreste::text,'') || '|' || coalesce(coornorte::text,'') AS clv, geom, cooreste, coornorte, zona, cota, departamento, provincia, distrito, ubicacion, descripcion, aaa, ala, uh, fechamonitoreo::date AS fechamonitoreo, fechamonitoreo::date + horamonitoreo::time AS horamonitoreo, orden, ce, ph, std, t, turbidez, nitratos, nitritos, cromohexavalente, cobre, manganeso, sulfatos, hierro, zinc, cloruros, coliformestotales, coliformestermotolerantes, escherichiacoli, "durezatotal", NULL::double precision AS "calcio", NULL::double precision AS "cloruro", NULL::double precision AS "potasio", NULL::double precision AS "sodio", NULL::double precision AS "amonio", NULL::double precision AS "magnesio", "observacion" AS "observaciones", CASE extract(MONTH FROM fechamonitoreo::date)::int WHEN 1 THEN 'ENERO' WHEN 2 THEN 'FEBRERO' WHEN 3 THEN 'MARZO' WHEN 4 THEN 'ABRIL' WHEN 5 THEN 'MAYO' WHEN 6 THEN 'JUNIO' WHEN 7 THEN 'JULIO' WHEN 8 THEN 'AGOSTO' WHEN 9 THEN 'SETIEMBRE' WHEN 10 THEN 'OCTUBRE' WHEN 11 THEN 'NOVIEMBRE' WHEN 12 THEN 'DICIEMBRE' END || ' ' || extract(YEAR FROM fechamonitoreo::date)::int AS campana, 'calidad agua' AS tipo
FROM calidadaguasuperficial2023.monitoreosuperficialdiciembre WHERE (fechamonitoreo IS NOT NULL OR cooreste IS NOT NULL OR coornorte IS NOT NULL OR ce IS NOT NULL OR ph IS NOT NULL OR turbidez IS NOT NULL)
UNION ALL
SELECT btrim(upper(coalesce(nullif(ubicacion,''),'(SIN NOMBRE)'))) || '|' || coalesce(cooreste::text,'') || '|' || coalesce(coornorte::text,'') AS clv, geom, cooreste, coornorte, zona, cota, departamento, provincia, distrito, ubicacion, descripcion, aaa, ala, uh, fechamonitoreo::date AS fechamonitoreo, fechamonitoreo::date + horamonitoreo::time AS horamonitoreo, orden, ce, ph, std, t, turbidez, nitratos, nitritos, cromohexavalente, cobre, manganeso, sulfatos, hierro, zinc, cloruros, coliformestotales, coliformestermotolerantes, escherichiacoli, "durezatotal", NULL::double precision AS "calcio", NULL::double precision AS "cloruro", NULL::double precision AS "potasio", NULL::double precision AS "sodio", NULL::double precision AS "amonio", NULL::double precision AS "magnesio", "observacion" AS "observaciones", CASE extract(MONTH FROM fechamonitoreo::date)::int WHEN 1 THEN 'ENERO' WHEN 2 THEN 'FEBRERO' WHEN 3 THEN 'MARZO' WHEN 4 THEN 'ABRIL' WHEN 5 THEN 'MAYO' WHEN 6 THEN 'JUNIO' WHEN 7 THEN 'JULIO' WHEN 8 THEN 'AGOSTO' WHEN 9 THEN 'SETIEMBRE' WHEN 10 THEN 'OCTUBRE' WHEN 11 THEN 'NOVIEMBRE' WHEN 12 THEN 'DICIEMBRE' END || ' ' || extract(YEAR FROM fechamonitoreo::date)::int AS campana, 'calidad agua' AS tipo
FROM calidadaguasuperficial2023.monitoreosuperficialmayo WHERE (fechamonitoreo IS NOT NULL OR cooreste IS NOT NULL OR coornorte IS NOT NULL OR ce IS NOT NULL OR ph IS NOT NULL OR turbidez IS NOT NULL)
UNION ALL
SELECT btrim(upper(coalesce(nullif(ubicacion,''),'(SIN NOMBRE)'))) || '|' || coalesce(cooreste::text,'') || '|' || coalesce(coornorte::text,'') AS clv, geom, cooreste, coornorte, zona, cota, departamento, provincia, distrito, ubicacion, descripcion, aaa, ala, uh, fechamonitoreo::date AS fechamonitoreo, fechamonitoreo::date + horamonitoreo::time AS horamonitoreo, orden, ce, ph, std, t, turbidez, nitratos, nitritos, cromohexavalente, cobre, manganeso, sulfatos, hierro, zinc, cloruros, coliformestotales, coliformestermotolerantes, escherichiacoli, "durezatotal", NULL::double precision AS "calcio", NULL::double precision AS "cloruro", NULL::double precision AS "potasio", NULL::double precision AS "sodio", NULL::double precision AS "amonio", NULL::double precision AS "magnesio", "observacion" AS "observaciones", CASE extract(MONTH FROM fechamonitoreo::date)::int WHEN 1 THEN 'ENERO' WHEN 2 THEN 'FEBRERO' WHEN 3 THEN 'MARZO' WHEN 4 THEN 'ABRIL' WHEN 5 THEN 'MAYO' WHEN 6 THEN 'JUNIO' WHEN 7 THEN 'JULIO' WHEN 8 THEN 'AGOSTO' WHEN 9 THEN 'SETIEMBRE' WHEN 10 THEN 'OCTUBRE' WHEN 11 THEN 'NOVIEMBRE' WHEN 12 THEN 'DICIEMBRE' END || ' ' || extract(YEAR FROM fechamonitoreo::date)::int AS campana, 'calidad agua' AS tipo
FROM calidadaguasuperficial2023.monitoreosuperficialoctubre WHERE (fechamonitoreo IS NOT NULL OR cooreste IS NOT NULL OR coornorte IS NOT NULL OR ce IS NOT NULL OR ph IS NOT NULL OR turbidez IS NOT NULL)
UNION ALL
SELECT btrim(upper(coalesce(nullif(ubicacion,''),'(SIN NOMBRE)'))) || '|' || coalesce(cooreste::text,'') || '|' || coalesce(coornorte::text,'') AS clv, geom, cooreste, coornorte, zona, cota, departamento, provincia, distrito, ubicacion, descripcion, aaa, ala, uh, fechamonitoreo::date AS fechamonitoreo, fechamonitoreo::date + horamonitoreo::time AS horamonitoreo, orden, ce, ph, std, t, turbidez, nitratos, nitritos, cromohexavalente, cobre, manganeso, sulfatos, hierro, zinc, cloruros, coliformestotales, coliformestermotolerantes, escherichiacoli, "durezatotal", "calcio", "cloruro", "potasio", "sodio", "amonio", "magnesio", "observacion" AS "observaciones", CASE extract(MONTH FROM fechamonitoreo::date)::int WHEN 1 THEN 'ENERO' WHEN 2 THEN 'FEBRERO' WHEN 3 THEN 'MARZO' WHEN 4 THEN 'ABRIL' WHEN 5 THEN 'MAYO' WHEN 6 THEN 'JUNIO' WHEN 7 THEN 'JULIO' WHEN 8 THEN 'AGOSTO' WHEN 9 THEN 'SETIEMBRE' WHEN 10 THEN 'OCTUBRE' WHEN 11 THEN 'NOVIEMBRE' WHEN 12 THEN 'DICIEMBRE' END || ' ' || extract(YEAR FROM fechamonitoreo::date)::int AS campana, 'calidad agua' AS tipo
FROM calidadaguasuperficial2024.monitoreosuperficialjunio WHERE (fechamonitoreo IS NOT NULL OR cooreste IS NOT NULL OR coornorte IS NOT NULL OR ce IS NOT NULL OR ph IS NOT NULL OR turbidez IS NOT NULL)
UNION ALL
SELECT btrim(upper(coalesce(nullif(ubicacion,''),'(SIN NOMBRE)'))) || '|' || coalesce(cooreste::text,'') || '|' || coalesce(coornorte::text,'') AS clv, geom, cooreste, coornorte, zona, cota, departamento, provincia, distrito, ubicacion, descripcion, aaa, ala, uh, fechamonitoreo::date AS fechamonitoreo, fechamonitoreo::date + horamonitoreo::time AS horamonitoreo, orden, ce, ph, std, t, turbidez, nitratos, nitritos, cromohexavalente, cobre, manganeso, sulfatos, hierro, zinc, cloruros, coliformestotales, coliformestermotolerantes, escherichiacoli, "durezatotal", "calcio", "cloruro", "potasio", "sodio", "amonio", "magnesio", "observacion" AS "observaciones", CASE extract(MONTH FROM fechamonitoreo::date)::int WHEN 1 THEN 'ENERO' WHEN 2 THEN 'FEBRERO' WHEN 3 THEN 'MARZO' WHEN 4 THEN 'ABRIL' WHEN 5 THEN 'MAYO' WHEN 6 THEN 'JUNIO' WHEN 7 THEN 'JULIO' WHEN 8 THEN 'AGOSTO' WHEN 9 THEN 'SETIEMBRE' WHEN 10 THEN 'OCTUBRE' WHEN 11 THEN 'NOVIEMBRE' WHEN 12 THEN 'DICIEMBRE' END || ' ' || extract(YEAR FROM fechamonitoreo::date)::int AS campana, 'calidad agua' AS tipo
FROM calidadaguasuperficial2024.monitoreosuperficialnoviembre WHERE (fechamonitoreo IS NOT NULL OR cooreste IS NOT NULL OR coornorte IS NOT NULL OR ce IS NOT NULL OR ph IS NOT NULL OR turbidez IS NOT NULL)
UNION ALL
SELECT btrim(upper(coalesce(nullif(ubicacion,''),'(SIN NOMBRE)'))) || '|' || coalesce(cooreste::text,'') || '|' || coalesce(coornorte::text,'') AS clv, geom, cooreste, coornorte, zona, cota, departamento, provincia, distrito, ubicacion, descripcion, aaa, ala, uh, fechamonitoreo::date AS fechamonitoreo, fechamonitoreo::date + horamonitoreo::time AS horamonitoreo, orden, ce, ph, std, t, turbidez, nitratos, nitritos, cromohexavalente, cobre, manganeso, sulfatos, hierro, zinc, cloruros, coliformestotales, coliformestermotolerantes, escherichiacoli, "durezatotal", "calcio", "cloruro", "potasio", "sodio", "amonio", "magnesio", "observaciones", CASE extract(MONTH FROM fechamonitoreo::date)::int WHEN 1 THEN 'ENERO' WHEN 2 THEN 'FEBRERO' WHEN 3 THEN 'MARZO' WHEN 4 THEN 'ABRIL' WHEN 5 THEN 'MAYO' WHEN 6 THEN 'JUNIO' WHEN 7 THEN 'JULIO' WHEN 8 THEN 'AGOSTO' WHEN 9 THEN 'SETIEMBRE' WHEN 10 THEN 'OCTUBRE' WHEN 11 THEN 'NOVIEMBRE' WHEN 12 THEN 'DICIEMBRE' END || ' ' || extract(YEAR FROM fechamonitoreo::date)::int AS campana, 'calidad agua' AS tipo
FROM calidadaguasuperficial2025.monitoreosuperficialdiciembre WHERE (fechamonitoreo IS NOT NULL OR cooreste IS NOT NULL OR coornorte IS NOT NULL OR ce IS NOT NULL OR ph IS NOT NULL OR turbidez IS NOT NULL)
UNION ALL
SELECT btrim(upper(coalesce(nullif(ubicacion,''),'(SIN NOMBRE)'))) || '|' || coalesce(cooreste::text,'') || '|' || coalesce(coornorte::text,'') AS clv, geom, cooreste, coornorte, zona, cota, departamento, provincia, distrito, ubicacion, descripcion, aaa, ala, uh, fechamonitoreo::date AS fechamonitoreo, fechamonitoreo::date + horamonitoreo::time AS horamonitoreo, orden, ce, ph, std, t, turbidez, nitratos, nitritos, cromohexavalente, cobre, manganeso, sulfatos, hierro, zinc, cloruros, coliformestotales, coliformestermotolerantes, escherichiacoli, "durezatotal", "calcio", "cloruro", "potasio", "sodio", "amonio", "magnesio", "observaciones", CASE extract(MONTH FROM fechamonitoreo::date)::int WHEN 1 THEN 'ENERO' WHEN 2 THEN 'FEBRERO' WHEN 3 THEN 'MARZO' WHEN 4 THEN 'ABRIL' WHEN 5 THEN 'MAYO' WHEN 6 THEN 'JUNIO' WHEN 7 THEN 'JULIO' WHEN 8 THEN 'AGOSTO' WHEN 9 THEN 'SETIEMBRE' WHEN 10 THEN 'OCTUBRE' WHEN 11 THEN 'NOVIEMBRE' WHEN 12 THEN 'DICIEMBRE' END || ' ' || extract(YEAR FROM fechamonitoreo::date)::int AS campana, 'calidad agua' AS tipo
FROM calidadaguasuperficial2025.monitoreosuperficialjulio WHERE (fechamonitoreo IS NOT NULL OR cooreste IS NOT NULL OR coornorte IS NOT NULL OR ce IS NOT NULL OR ph IS NOT NULL OR turbidez IS NOT NULL)
UNION ALL
SELECT btrim(upper(coalesce(nullif(ubicacion,''),'(SIN NOMBRE)'))) || '|' || coalesce(cooreste::text,'') || '|' || coalesce(coornorte::text,'') AS clv, geom, cooreste, coornorte, zona, cota, departamento, provincia, distrito, ubicacion, descripcion, aaa, ala, uh, fechamonitoreo::date AS fechamonitoreo, fechamonitoreo::date + horamonitoreo::time AS horamonitoreo, orden, ce, ph, std, t, turbidez, nitratos, nitritos, cromohexavalente, cobre, manganeso, sulfatos, hierro, zinc, cloruros, coliformestotales, coliformestermotolerantes, escherichiacoli, "durezatotal", "calcio", "cloruro", "potasio", "sodio", "amonio", "magnesio", "observaciones", CASE extract(MONTH FROM fechamonitoreo::date)::int WHEN 1 THEN 'ENERO' WHEN 2 THEN 'FEBRERO' WHEN 3 THEN 'MARZO' WHEN 4 THEN 'ABRIL' WHEN 5 THEN 'MAYO' WHEN 6 THEN 'JUNIO' WHEN 7 THEN 'JULIO' WHEN 8 THEN 'AGOSTO' WHEN 9 THEN 'SETIEMBRE' WHEN 10 THEN 'OCTUBRE' WHEN 11 THEN 'NOVIEMBRE' WHEN 12 THEN 'DICIEMBRE' END || ' ' || extract(YEAR FROM fechamonitoreo::date)::int AS campana, 'calidad agua' AS tipo
FROM calidadaguasuperficial2025.monitoreosuperficialmarzo WHERE (fechamonitoreo IS NOT NULL OR cooreste IS NOT NULL OR coornorte IS NOT NULL OR ce IS NOT NULL OR ph IS NOT NULL OR turbidez IS NOT NULL)
UNION ALL
SELECT btrim(upper(coalesce(nullif(ubicacion,''),'(SIN NOMBRE)'))) || '|' || coalesce(cooreste::text,'') || '|' || coalesce(coornorte::text,'') AS clv, geom, cooreste, coornorte, zona, cota, departamento, provincia, distrito, ubicacion, descripcion, aaa, ala, uh, fechamonitoreo::date AS fechamonitoreo, fechamonitoreo::date + horamonitoreo::time AS horamonitoreo, orden, ce, ph, std, t, turbidez, nitratos, nitritos, cromohexavalente, cobre, manganeso, sulfatos, hierro, zinc, cloruros, coliformestotales, coliformestermotolerantes, escherichiacoli, "durezatotal", "calcio", "cloruro", "potasio", "sodio", "amonio", "magnesio", "observaciones", CASE extract(MONTH FROM fechamonitoreo::date)::int WHEN 1 THEN 'ENERO' WHEN 2 THEN 'FEBRERO' WHEN 3 THEN 'MARZO' WHEN 4 THEN 'ABRIL' WHEN 5 THEN 'MAYO' WHEN 6 THEN 'JUNIO' WHEN 7 THEN 'JULIO' WHEN 8 THEN 'AGOSTO' WHEN 9 THEN 'SETIEMBRE' WHEN 10 THEN 'OCTUBRE' WHEN 11 THEN 'NOVIEMBRE' WHEN 12 THEN 'DICIEMBRE' END || ' ' || extract(YEAR FROM fechamonitoreo::date)::int AS campana, 'calidad agua' AS tipo
FROM calidadaguasuperficial2025.monitoreosuperficialnoviembre WHERE (fechamonitoreo IS NOT NULL OR cooreste IS NOT NULL OR coornorte IS NOT NULL OR ce IS NOT NULL OR ph IS NOT NULL OR turbidez IS NOT NULL)
UNION ALL
SELECT btrim(upper(coalesce(nullif(ubicacion,''),'(SIN NOMBRE)'))) || '|' || coalesce(cooreste::text,'') || '|' || coalesce(coornorte::text,'') AS clv, geom, cooreste, coornorte, zona, cota, departamento, provincia, distrito, ubicacion, descripcion, aaa, ala, uh, fechamonitoreo::date AS fechamonitoreo, fechamonitoreo::date + horamonitoreo::time AS horamonitoreo, orden, ce, ph, std, t, turbidez, nitratos, nitritos, cromohexavalente, cobre, manganeso, sulfatos, hierro, zinc, cloruros, coliformestotales, coliformestermotolerantes, escherichiacoli, "durezatotal", "calcio", "cloruro", "potasio", "sodio", "amonio", "magnesio", "observaciones", CASE extract(MONTH FROM fechamonitoreo::date)::int WHEN 1 THEN 'ENERO' WHEN 2 THEN 'FEBRERO' WHEN 3 THEN 'MARZO' WHEN 4 THEN 'ABRIL' WHEN 5 THEN 'MAYO' WHEN 6 THEN 'JUNIO' WHEN 7 THEN 'JULIO' WHEN 8 THEN 'AGOSTO' WHEN 9 THEN 'SETIEMBRE' WHEN 10 THEN 'OCTUBRE' WHEN 11 THEN 'NOVIEMBRE' WHEN 12 THEN 'DICIEMBRE' END || ' ' || extract(YEAR FROM fechamonitoreo::date)::int AS campana, 'calidad agua' AS tipo
FROM calidadaguasuperficial2026.monitoreosuperficialagosto WHERE (fechamonitoreo IS NOT NULL OR cooreste IS NOT NULL OR coornorte IS NOT NULL OR ce IS NOT NULL OR ph IS NOT NULL OR turbidez IS NOT NULL)
UNION ALL
SELECT btrim(upper(coalesce(nullif(ubicacion,''),'(SIN NOMBRE)'))) || '|' || coalesce(cooreste::text,'') || '|' || coalesce(coornorte::text,'') AS clv, geom, cooreste, coornorte, zona, cota, departamento, provincia, distrito, ubicacion, descripcion, aaa, ala, uh, fechamonitoreo::date AS fechamonitoreo, fechamonitoreo::date + horamonitoreo::time AS horamonitoreo, orden, ce, ph, std, t, turbidez, nitratos, nitritos, cromohexavalente, cobre, manganeso, sulfatos, hierro, zinc, cloruros, coliformestotales, coliformestermotolerantes, escherichiacoli, "durezatotal", "calcio", "cloruro", "potasio", "sodio", "amonio", "magnesio", "observaciones", CASE extract(MONTH FROM fechamonitoreo::date)::int WHEN 1 THEN 'ENERO' WHEN 2 THEN 'FEBRERO' WHEN 3 THEN 'MARZO' WHEN 4 THEN 'ABRIL' WHEN 5 THEN 'MAYO' WHEN 6 THEN 'JUNIO' WHEN 7 THEN 'JULIO' WHEN 8 THEN 'AGOSTO' WHEN 9 THEN 'SETIEMBRE' WHEN 10 THEN 'OCTUBRE' WHEN 11 THEN 'NOVIEMBRE' WHEN 12 THEN 'DICIEMBRE' END || ' ' || extract(YEAR FROM fechamonitoreo::date)::int AS campana, 'calidad agua' AS tipo
FROM calidadaguasuperficial2026.monitoreosuperficialmarzo WHERE (fechamonitoreo IS NOT NULL OR cooreste IS NOT NULL OR coornorte IS NOT NULL OR ce IS NOT NULL OR ph IS NOT NULL OR turbidez IS NOT NULL)
